erDiagram
  redcap_actions }o--|| redcap_surveys : "survey_id"
  redcap_ai_log }o--|| redcap_user_information : "user_id"
  redcap_alerts }o--|| redcap_projects : "project_id"
  redcap_alerts_recurrence }o--|| redcap_events_metadata : "event_id"
  redcap_alerts_sent }o--|| redcap_events_metadata : "event_id"
  redcap_alerts_sent_log }o--|| redcap_alerts_sent : "alert_sent_id"
  redcap_auth }o--|| redcap_auth_questions : "password_question"
  redcap_cache }o--|| redcap_projects : "project_id"
  redcap_cde_field_mapping }o--|| redcap_projects : "project_id"
  redcap_crons }o--|| redcap_external_modules : "external_module_id"
  redcap_crons_datediff }o--|| redcap_projects : "project_id"
  redcap_crons_history }o--|| redcap_crons : "cron_id"
  redcap_custom_queries_folders_items }o--|| redcap_custom_queries : "qid"
  redcap_data_access_groups }o--|| redcap_projects : "project_id"
  redcap_data_access_groups_users }o--|| redcap_projects : "project_id"
  redcap_data_dictionaries }o--|| redcap_user_information : "ui_id"
  redcap_data_import }o--|| redcap_user_information : "user_id"
  redcap_data_import_rows }o--|| redcap_data_import : "import_id"
  redcap_data_quality_resolutions }o--|| redcap_user_information : "user_id"
  redcap_data_quality_rules }o--|| redcap_projects : "project_id"
  redcap_data_quality_status }o--|| redcap_data_quality_rules : "rule_id"
  redcap_ddp_log_view }o--|| redcap_user_information : "user_id"
  redcap_ddp_log_view_data }o--|| redcap_ddp_log_view : "ml_id"
  redcap_ddp_mapping }o--|| redcap_projects : "project_id"
  redcap_ddp_preview_fields }o--|| redcap_projects : "project_id"
  redcap_ddp_records }o--|| redcap_projects : "project_id"
  redcap_ddp_records_data }o--|| redcap_ddp_records : "mr_id"
  redcap_descriptive_popups }o--|| redcap_projects : "project_id"
  redcap_docs }o--|| redcap_projects : "project_id"
  redcap_docs_attachments }o--|| redcap_docs : "docs_id"
  redcap_docs_folders }o--|| redcap_user_roles : "role_id"
  redcap_docs_folders_files }o--|| redcap_docs_folders : "folder_id"
  redcap_docs_share }o--|| redcap_docs : "docs_id"
  redcap_docs_to_edocs }o--|| redcap_docs : "docs_id"
  redcap_econsent }o--|| redcap_surveys : "survey_id"
  redcap_econsent_forms }o--|| redcap_user_information : "uploader"
  redcap_edocs_data_mapping }o--|| redcap_projects : "project_id"
  redcap_edocs_metadata }o--|| redcap_projects : "project_id"
  redcap_ehr_access_tokens }o--|| redcap_user_information : "token_owner"
  redcap_ehr_datamart_revisions }o--|| redcap_user_information : "user_id"
  redcap_ehr_fhir_logs }o--|| redcap_user_information : "user_id"
  redcap_ehr_import_counts }o--|| redcap_projects : "project_id"
  redcap_ehr_resource_import_details }o--|| redcap_ehr_resource_imports : "ehr_import_count_id"
  redcap_ehr_resource_imports }o--|| redcap_projects : "project_id"
  redcap_ehr_token_rules }o--|| redcap_user_information : "user_id"
  redcap_ehr_user_map }o--|| redcap_ehr_settings : "ehr_id"
  redcap_ehr_user_projects }o--|| redcap_user_information : "redcap_userid"
  redcap_email_users_messages }o--|| redcap_user_information : "sent_by"
  redcap_error_log }o--|| redcap_log_view : "log_view_id"
  redcap_esignatures }o--|| redcap_projects : "project_id"
  redcap_events_arms }o--|| redcap_projects : "project_id"
  redcap_events_calendar }o--|| redcap_projects : "project_id"
  redcap_events_calendar_feed }o--|| redcap_user_information : "userid"
  redcap_events_forms }o--|| redcap_events_metadata : "event_id"
  redcap_events_metadata }o--|| redcap_events_arms : "arm_id"
  redcap_events_repeat }o--|| redcap_events_metadata : "event_id"
  redcap_external_links }o--|| redcap_projects : "project_id"
  redcap_external_links_dags }o--|| redcap_data_access_groups : "group_id"
  redcap_external_links_exclude_projects }o--|| redcap_projects : "project_id"
  redcap_external_links_users }o--|| redcap_external_links : "ext_id"
  redcap_external_module_settings }o--|| redcap_projects : "project_id"
  redcap_external_modules_log_parameters }o--|| redcap_external_modules_log : "log_id"
  redcap_folders }o--|| redcap_user_information : "ui_id"
  redcap_folders_projects }o--|| redcap_user_information : "ui_id"
  redcap_form_display_logic_conditions }o--|| redcap_projects : "project_id"
  redcap_form_display_logic_targets }o--|| redcap_events_metadata : "event_id"
  redcap_forms }o--|| redcap_projects : "project_id"
  redcap_forms_temp }o--|| redcap_projects : "project_id"
  redcap_instrument_zip }o--|| redcap_instrument_zip_authors : "iza_id"
  redcap_library_map }o--|| redcap_projects : "project_id"
  redcap_locking_data }o--|| redcap_projects : "project_id"
  redcap_locking_labels }o--|| redcap_projects : "project_id"
  redcap_locking_records }o--|| redcap_projects : "project_id"
  redcap_locking_records_pdf_archive }o--|| redcap_projects : "project_id"
  redcap_log_view_requests }o--|| redcap_user_information : "ui_id"
  redcap_messages }o--|| redcap_messages_threads : "thread_id"
  redcap_messages_recipients }o--|| redcap_messages_threads : "thread_id"
  redcap_messages_status }o--|| redcap_user_information : "recipient_user_id"
  redcap_messages_threads }o--|| redcap_projects : "project_id"
  redcap_metadata }o--|| redcap_projects : "project_id"
  redcap_metadata_archive }o--|| redcap_projects : "project_id"
  redcap_metadata_prod_revisions }o--|| redcap_user_information : "ui_id_requester"
  redcap_metadata_temp }o--|| redcap_projects : "project_id"
  redcap_mobile_app_devices }o--|| redcap_projects : "project_id"
  redcap_mobile_app_files }o--|| redcap_user_information : "user_id"
  redcap_mobile_app_log }o--|| redcap_user_information : "ui_id"
  redcap_multilanguage_config }o--|| redcap_projects : "project_id"
  redcap_multilanguage_config_temp }o--|| redcap_projects : "project_id"
  redcap_multilanguage_metadata }o--|| redcap_projects : "project_id"
  redcap_multilanguage_metadata_temp }o--|| redcap_projects : "project_id"
  redcap_multilanguage_snapshots }o--|| redcap_projects : "project_id"
  redcap_multilanguage_ui }o--|| redcap_projects : "project_id"
  redcap_multilanguage_ui_temp }o--|| redcap_projects : "project_id"
  redcap_mycap_aboutpages }o--|| redcap_projects : "project_id"
  redcap_mycap_contacts }o--|| redcap_projects : "project_id"
  redcap_mycap_links }o--|| redcap_projects : "project_id"
  redcap_mycap_message_notifications }o--|| redcap_projects : "project_id"
  redcap_mycap_messages }o--|| redcap_projects : "project_id"
  redcap_mycap_participants }o--|| redcap_projects : "project_id"
  redcap_mycap_projectfiles }o--|| redcap_mycap_projects : "project_code"
  redcap_mycap_projects }o--|| redcap_projects : "project_id"
  redcap_mycap_syncissuefiles }o--|| redcap_mycap_syncissues : "uuid"
  redcap_mycap_syncissues }o--|| redcap_events_metadata : "event_id"
  redcap_mycap_tasks }o--|| redcap_projects : "project_id"
  redcap_mycap_tasks_schedules }o--|| redcap_mycap_tasks : "task_id"
  redcap_mycap_themes }o--|| redcap_projects : "project_id"
  redcap_new_record_cache }o--|| redcap_projects : "project_id"
  redcap_outgoing_email_sms_identifiers }o--|| redcap_surveys_scheduler_queue : "ssq_id"
  redcap_outgoing_email_sms_log }o--|| redcap_projects : "project_id"
  redcap_pdf_image_cache }o--|| redcap_edocs_metadata : "pdf_doc_id"
  redcap_pdf_snapshots }o--|| redcap_surveys : "trigger_surveycomplete_survey_id"
  redcap_pdf_snapshots_triggered }o--|| redcap_pdf_snapshots : "snapshot_id"
  redcap_project_checklist }o--|| redcap_projects : "project_id"
  redcap_project_dashboards }o--|| redcap_projects : "project_id"
  redcap_project_dashboards_access_dags }o--|| redcap_data_access_groups : "group_id"
  redcap_project_dashboards_access_roles }o--|| redcap_user_roles : "role_id"
  redcap_project_dashboards_access_users }o--|| redcap_project_dashboards : "dash_id"
  redcap_project_dashboards_folders }o--|| redcap_projects : "project_id"
  redcap_project_dashboards_folders_items }o--|| redcap_project_dashboards_folders : "folder_id"
  redcap_projects }o--|| redcap_projects : "template_id"
  redcap_projects_templates }o--|| redcap_projects : "project_id"
  redcap_projects_user_hidden }o--|| redcap_user_information : "ui_id"
  redcap_pub_articles }o--|| redcap_pub_sources : "pubsrc_id"
  redcap_pub_authors }o--|| redcap_pub_articles : "article_id"
  redcap_pub_matches }o--|| redcap_projects : "project_id"
  redcap_pub_mesh_terms }o--|| redcap_pub_articles : "article_id"
  redcap_randomization }o--|| redcap_events_metadata : "trigger_event_id"
  redcap_randomization_allocation }o--|| redcap_randomization : "rid"
  redcap_record_background_delete }o--|| redcap_user_information : "user_id"
  redcap_record_background_delete_items }o--|| redcap_record_background_delete : "delete_id"
  redcap_record_counts }o--|| redcap_projects : "project_id"
  redcap_record_dashboards }o--|| redcap_events_metadata : "sort_event_id"
  redcap_record_list }o--|| redcap_projects : "project_id"
  redcap_reports }o--|| redcap_projects : "project_id"
  redcap_reports_access_dags }o--|| redcap_reports : "report_id"
  redcap_reports_access_roles }o--|| redcap_user_roles : "role_id"
  redcap_reports_access_users }o--|| redcap_reports : "report_id"
  redcap_reports_ai_prompts }o--|| redcap_reports : "report_id"
  redcap_reports_edit_access_dags }o--|| redcap_reports : "report_id"
  redcap_reports_edit_access_roles }o--|| redcap_user_roles : "role_id"
  redcap_reports_edit_access_users }o--|| redcap_reports : "report_id"
  redcap_reports_fields }o--|| redcap_reports : "report_id"
  redcap_reports_filter_dags }o--|| redcap_reports : "report_id"
  redcap_reports_filter_events }o--|| redcap_reports : "report_id"
  redcap_reports_folders }o--|| redcap_projects : "project_id"
  redcap_reports_folders_items }o--|| redcap_reports : "report_id"
  redcap_rewards_access_token }o--|| redcap_rewards_providers : "provider_id"
  redcap_rewards_actions }o--|| redcap_projects : "project_id"
  redcap_rewards_emails }o--|| redcap_user_information : "sent_by"
  redcap_rewards_logs }o--|| redcap_projects : "project_id"
  redcap_rewards_orders }o--|| redcap_rewards_reward_option : "reward_option_id"
  redcap_rewards_project_providers }o--|| redcap_rewards_providers : "provider_id"
  redcap_rewards_project_settings }o--|| redcap_projects : "project_id"
  redcap_rewards_reward_option }o--|| redcap_projects : "project_id"
  redcap_rewards_settings }o--|| redcap_rewards_providers : "provider_id"
  redcap_rewards_user_permissions }o--|| redcap_user_information : "user_id"
  redcap_sendit_recipients }o--|| redcap_sendit_docs : "document_id"
  redcap_surveys }o--|| redcap_surveys_themes : "theme"
  redcap_surveys_emails }o--|| redcap_surveys : "survey_id"
  redcap_surveys_emails_recipients }o--|| redcap_surveys_participants : "participant_id"
  redcap_surveys_erase_twilio_log }o--|| redcap_projects : "project_id"
  redcap_surveys_login }o--|| redcap_surveys_response : "response_id"
  redcap_surveys_participants }o--|| redcap_surveys : "survey_id"
  redcap_surveys_pdf_archive }o--|| redcap_surveys : "survey_id"
  redcap_surveys_phone_codes }o--|| redcap_projects : "project_id"
  redcap_surveys_queue }o--|| redcap_surveys : "survey_id"
  redcap_surveys_queue_hashes }o--|| redcap_projects : "project_id"
  redcap_surveys_response }o--|| redcap_surveys_participants : "participant_id"
  redcap_surveys_scheduler }o--|| redcap_surveys : "survey_id"
  redcap_surveys_scheduler_queue }o--|| redcap_surveys_scheduler : "ss_id"
  redcap_surveys_scheduler_recurrence }o--|| redcap_surveys_scheduler : "ss_id"
  redcap_surveys_short_codes }o--|| redcap_surveys_participants : "participant_id"
  redcap_surveys_themes }o--|| redcap_user_information : "ui_id"
  redcap_todo_list }o--|| redcap_user_information : "request_from"
  redcap_twilio_credentials_temp }o--|| redcap_todo_list : "request_id"
  redcap_twilio_error_log }o--|| redcap_surveys_scheduler_queue : "ssq_id"
  redcap_two_factor_response }o--|| redcap_user_information : "user_id"
  redcap_user_rights }o--|| redcap_user_roles : "role_id"
  redcap_user_roles }o--|| redcap_projects : "project_id"
  redcap_web_service_cache }o--|| redcap_projects : "project_id"
