export const SEED_IDS = {
  USER_ADMIN: "clseedadmin000000000000",
  USER_MANAGER: "clseedmanager0000000000",
  USER_MEMBER: "clseedmember00000000000",
  ORGANIZATION: "clseedorg0000000000000",
  PROJECT: "clseedproject000000000",
  ENV_DEV: "clseedenvdev0000000000",
  ENV_PROD: "clseedenvprod000000000",
  SURVEY_KITCHEN_SINK: "clseedsurveykitchen00",
  SURVEY_CSAT: "clseedsurveycsat000000",
  SURVEY_DRAFT: "clseedsurveydraft00000",
  SURVEY_COMPLETED: "clseedsurveycomplete00",
  // Clinical template seed projects (one per template)
  CLINICAL_PROJECT_CLASSIC_DB: "clclinprojclassicdb000",
  CLINICAL_PROJECT_LONG_2_ARMS: "clclinprojlong2arms000",
  CLINICAL_PROJECT_SINGLE_SURVEY: "clclinprojsnglsurvey00",
  CLINICAL_PROJECT_LONG_1_ARM: "clclinprojlong1arm0000",
  CLINICAL_PROJECT_BASIC_DEMOGRAPHY: "clclinprojbasicdemog00",
  CLINICAL_PROJECT_PROJECT_TRACKING: "clclinprojprojtrack000",
  CLINICAL_PROJECT_RCT: "clclinprojrct000000000",
  CLINICAL_PROJECT_CANCER_BIOBANK: "clclinprojcancerbbnk00",
  CLINICAL_PROJECT_SURVEYS_CLASSIC: "clclinprojmultisrvcls0",
  CLINICAL_PROJECT_SURVEYS_LONG: "clclinprojmultisrvlng0",
  CLINICAL_PROJECT_PIPING: "clclinprojpipingex0000",
  CLINICAL_PROJECT_REPEATING: "clclinprojrptistr00000",
  CLINICAL_PROJECT_FIELD_EMBEDDING: "clclinprojfldembdg000",
  CLINICAL_PROJECT_DASHBOARDS: "clclinprojdashbrd00000",
  CLINICAL_PROJECT_MYCAP: "clclinprojmycap000000",
  // Clinical template seed studies (one per template)
  CLINICAL_STUDY_CLASSIC_DB: "clclinstdyclassicdb000",
  CLINICAL_STUDY_LONG_2_ARMS: "clclinstdylong2arms000",
  CLINICAL_STUDY_SINGLE_SURVEY: "clclinstdysnglsurvey00",
  CLINICAL_STUDY_LONG_1_ARM: "clclinstdylong1arm0000",
  CLINICAL_STUDY_BASIC_DEMOGRAPHY: "clclinstdybasicdemog00",
  CLINICAL_STUDY_PROJECT_TRACKING: "clclinstdyprojtrack000",
  CLINICAL_STUDY_RCT: "clclinstdyrct000000000",
  CLINICAL_STUDY_CANCER_BIOBANK: "clclinstdycancerbbnk00",
  CLINICAL_STUDY_SURVEYS_CLASSIC: "clclinstdymultisrvcls0",
  CLINICAL_STUDY_SURVEYS_LONG: "clclinstdymultisrvlng0",
  CLINICAL_STUDY_PIPING: "clclinstdypipingex0000",
  CLINICAL_STUDY_REPEATING: "clclinstdyrptistr00000",
  CLINICAL_STUDY_FIELD_EMBEDDING: "clclinstdyfldembdg000",
  CLINICAL_STUDY_DASHBOARDS: "clclinstdydashbrd00000",
  CLINICAL_STUDY_MYCAP: "clclinstdymycap0000000",
} as const;

export const SEED_CREDENTIALS = {
  ADMIN: { email: "admin@continium.com", password: "Password#123" },
  MANAGER: { email: "manager@continium.com", password: "Password#123" },
  MEMBER: { email: "member@continium.com", password: "Password#123" },
} as const;
