// AUTO-GENERATED by apps/web/modules/clinical/onboarding/scripts/convert-redcap-sql.ts
// Source: redcap/redcap_v15.8.4/Resources/sql/create_demo_db5.sql
// Do not edit by hand — regenerate by running the converter.
import type { TClinicalTemplate } from "../template-types";

export const basicDemographyTemplate: TClinicalTemplate = {
  "key": "basic_demography",
  "name": "Basic Demography",
  "description": "Minimal demographics-only protocol — useful for quick prototyping or capturing a demographics screening instrument.",
  "purpose": "practice",
  "source": {
    "redcapDemo": "Basic Demography",
    "sourceFile": "redcap/redcap_v15.8.4/Resources/sql/create_demo_db5.sql"
  },
  "arms": [
    {
      "name": "Arm 1",
      "position": 0,
      "events": [
        {
          "name": "Event 1",
          "position": 0,
          "dayOffset": 0,
          "windowDays": null,
          "instrumentBindings": [
            {
              "instrumentKey": "demographics",
              "required": true,
              "repeating": false
            }
          ]
        }
      ]
    }
  ],
  "instruments": [
    {
      "key": "demographics",
      "displayName": "Demographics",
      "fields": [
        {
          "key": "record_id",
          "label": "Study ID",
          "type": "TEXT",
          "required": false,
          "position": 0,
          "choicesJson": null
        },
        {
          "key": "first_name",
          "label": "First Name",
          "type": "TEXT",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "last_name",
          "label": "Last Name",
          "type": "TEXT",
          "required": false,
          "position": 2,
          "choicesJson": null
        },
        {
          "key": "address",
          "label": "Street, City, State, ZIP",
          "type": "TEXT",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "telephone",
          "label": "Phone number",
          "type": "TEXT",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "email",
          "label": "E-mail",
          "type": "TEXT",
          "required": false,
          "position": 5,
          "choicesJson": null
        },
        {
          "key": "dob",
          "label": "Date of birth",
          "type": "DATE",
          "required": false,
          "position": 6,
          "choicesJson": null
        },
        {
          "key": "age",
          "label": "Age (years)",
          "type": "TEXT",
          "required": false,
          "position": 7,
          "choicesJson": null,
          "note": "Imported from REDCap calc field; calculation logic is not migrated."
        },
        {
          "key": "ethnicity",
          "label": "Ethnicity",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 8,
          "choicesJson": [
            {
              "value": "0",
              "label": "Hispanic or Latino"
            },
            {
              "value": "1",
              "label": "NOT Hispanic or Latino"
            },
            {
              "value": "2",
              "label": "Unknown / Not Reported"
            }
          ]
        },
        {
          "key": "race",
          "label": "Race",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 9,
          "choicesJson": [
            {
              "value": "0",
              "label": "American Indian/Alaska Native"
            },
            {
              "value": "1",
              "label": "Asian"
            },
            {
              "value": "2",
              "label": "Native Hawaiian or Other Pacific Islander"
            },
            {
              "value": "3",
              "label": "Black or African American"
            },
            {
              "value": "4",
              "label": "White"
            },
            {
              "value": "5",
              "label": "More Than One Race"
            },
            {
              "value": "6",
              "label": "Unknown / Not Reported"
            }
          ]
        },
        {
          "key": "sex",
          "label": "sex",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 10,
          "choicesJson": [
            {
              "value": "0",
              "label": "Female"
            },
            {
              "value": "1",
              "label": "Male"
            },
            {
              "value": "2",
              "label": "Other"
            },
            {
              "value": "3",
              "label": "Prefer not to say"
            }
          ]
        },
        {
          "key": "height",
          "label": "Height (cm)",
          "type": "TEXT",
          "required": false,
          "position": 11,
          "choicesJson": null
        },
        {
          "key": "weight",
          "label": "Weight (kilograms)",
          "type": "TEXT",
          "required": false,
          "position": 12,
          "choicesJson": null
        },
        {
          "key": "bmi",
          "label": "BMI",
          "type": "TEXT",
          "required": false,
          "position": 13,
          "choicesJson": null,
          "note": "Imported from REDCap calc field; calculation logic is not migrated."
        },
        {
          "key": "comments",
          "label": "Comments",
          "type": "TEXT",
          "required": false,
          "position": 14,
          "choicesJson": null
        },
        {
          "key": "demographics_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 15,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    }
  ]
} as TClinicalTemplate;
