// AUTO-GENERATED by apps/web/modules/clinical/onboarding/scripts/convert-redcap-sql.ts
// Source: redcap/redcap_v15.8.4/Resources/sql/create_demo_db8.sql
// Do not edit by hand — regenerate by running the converter.
import type { TClinicalTemplate } from "../template-types";

export const cancerTissueBiobankTemplate: TClinicalTemplate = {
  "key": "cancer_tissue_biobank",
  "name": "Human Cancer Tissue Biobank",
  "description": "Tissue biobank schema covering specimen tracking, pathology, and donor consent.",
  "purpose": "research",
  "source": {
    "redcapDemo": "Human Cancer Tissue Biobank",
    "sourceFile": "redcap/redcap_v15.8.4/Resources/sql/create_demo_db8.sql"
  },
  "arms": [
    {
      "name": "Arm 1",
      "position": 0,
      "events": [
        {
          "name": "Event 1",
          "position": 0,
          "dayOffset": 0,
          "windowDays": null,
          "instrumentBindings": [
            {
              "instrumentKey": "id_shipping",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "pathology_review",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "tma_information",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "slide_tracking",
              "required": true,
              "repeating": false
            }
          ]
        }
      ]
    }
  ],
  "instruments": [
    {
      "key": "id_shipping",
      "displayName": "Id Shipping",
      "fields": [
        {
          "key": "lab_id",
          "label": "Lab ID",
          "type": "TEXT",
          "required": false,
          "position": 0,
          "choicesJson": null
        },
        {
          "key": "trc_id",
          "label": "TRC ID",
          "type": "TEXT",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "first_name",
          "label": "First Name",
          "type": "TEXT",
          "required": true,
          "position": 2,
          "choicesJson": null
        },
        {
          "key": "middle_name",
          "label": "Middle Name",
          "type": "TEXT",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "last_name",
          "label": "Last Name",
          "type": "TEXT",
          "required": true,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "suffix",
          "label": "Suffix",
          "type": "TEXT",
          "required": false,
          "position": 5,
          "choicesJson": null
        },
        {
          "key": "date_of_birth",
          "label": "Date of Birth",
          "type": "DATE",
          "required": false,
          "position": 6,
          "choicesJson": null
        },
        {
          "key": "age",
          "label": "Age",
          "type": "TEXT",
          "required": false,
          "position": 7,
          "choicesJson": null
        },
        {
          "key": "facility_name",
          "label": "Facility_Name",
          "type": "TEXT",
          "required": false,
          "position": 8,
          "choicesJson": null
        },
        {
          "key": "facility_city",
          "label": "Facility_City",
          "type": "TEXT",
          "required": false,
          "position": 9,
          "choicesJson": null
        },
        {
          "key": "facility_state",
          "label": "Facility_State",
          "type": "TEXT",
          "required": false,
          "position": 10,
          "choicesJson": null
        },
        {
          "key": "receivedate",
          "label": "ReceiveDate",
          "type": "DATE",
          "required": true,
          "position": 11,
          "choicesJson": null
        },
        {
          "key": "shipmethod",
          "label": "ShipMethod",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 12,
          "choicesJson": [
            {
              "value": "1",
              "label": "FedEx"
            },
            {
              "value": "2",
              "label": "USPS"
            },
            {
              "value": "3",
              "label": "UPS"
            },
            {
              "value": "4",
              "label": "ByPerson"
            },
            {
              "value": "5",
              "label": "Others"
            }
          ]
        },
        {
          "key": "trackingnumber",
          "label": "ReceiveTracking",
          "type": "TEXT",
          "required": false,
          "position": 13,
          "choicesJson": null
        },
        {
          "key": "pathaccnumber",
          "label": "PathAccNumber",
          "type": "TEXT",
          "required": true,
          "position": 14,
          "choicesJson": null
        },
        {
          "key": "otheraccnumber2",
          "label": "OtherAccNumber",
          "type": "TEXT",
          "required": false,
          "position": 15,
          "choicesJson": null
        },
        {
          "key": "blk_no_received",
          "label": "Block_ Received",
          "type": "TEXT",
          "required": false,
          "position": 16,
          "choicesJson": null
        },
        {
          "key": "stainedslide_received",
          "label": "StainedSlide_Received",
          "type": "TEXT",
          "required": false,
          "position": 17,
          "choicesJson": null
        },
        {
          "key": "unstainedslide_received",
          "label": "UnstainedSlide_Received",
          "type": "TEXT",
          "required": false,
          "position": 18,
          "choicesJson": null
        },
        {
          "key": "return_needed",
          "label": "Return_Needed?",
          "type": "BOOLEAN",
          "required": false,
          "position": 19,
          "choicesJson": null
        },
        {
          "key": "return_date",
          "label": "ReturnDate",
          "type": "DATE",
          "required": false,
          "position": 20,
          "choicesJson": null
        },
        {
          "key": "return_tracking",
          "label": "ReturnTracking",
          "type": "TEXT",
          "required": false,
          "position": 21,
          "choicesJson": null
        },
        {
          "key": "labcirculation_time",
          "label": "LabCirculation_time",
          "type": "TEXT",
          "required": false,
          "position": 22,
          "choicesJson": null,
          "note": "Imported from REDCap calc field; calculation logic is not migrated."
        },
        {
          "key": "followup_note",
          "label": "FollowUp_Note",
          "type": "TEXT",
          "required": false,
          "position": 23,
          "choicesJson": null
        },
        {
          "key": "secondtime_getsample",
          "label": "2nd_Time_Receive",
          "type": "BOOLEAN",
          "required": false,
          "position": 24,
          "choicesJson": null
        },
        {
          "key": "follow_up_needed2",
          "label": "Follow up needed?",
          "type": "BOOLEAN",
          "required": false,
          "position": 25,
          "choicesJson": null
        },
        {
          "key": "collection_note2",
          "label": "FollowUp_Note2",
          "type": "TEXT",
          "required": false,
          "position": 26,
          "choicesJson": null
        },
        {
          "key": "samefacasbefore",
          "label": "SameFacilityAsBefore?",
          "type": "BOOLEAN",
          "required": false,
          "position": 27,
          "choicesJson": null
        },
        {
          "key": "facility_name2",
          "label": "Facility_Name2",
          "type": "TEXT",
          "required": false,
          "position": 28,
          "choicesJson": null
        },
        {
          "key": "facility_city2",
          "label": "Facility_City2",
          "type": "TEXT",
          "required": false,
          "position": 29,
          "choicesJson": null
        },
        {
          "key": "facility_state2",
          "label": "Facility_State2",
          "type": "TEXT",
          "required": false,
          "position": 30,
          "choicesJson": null
        },
        {
          "key": "receivedate2",
          "label": "ReceiveDate2",
          "type": "DATE",
          "required": false,
          "position": 31,
          "choicesJson": null
        },
        {
          "key": "shipmethod2",
          "label": "ShipMethod2",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 32,
          "choicesJson": [
            {
              "value": "1",
              "label": "FedEx"
            },
            {
              "value": "2",
              "label": "USPS"
            },
            {
              "value": "3",
              "label": "UPS"
            },
            {
              "value": "4",
              "label": "ByPerson"
            },
            {
              "value": "5",
              "label": "Others"
            }
          ]
        },
        {
          "key": "receivetracking2",
          "label": "ReceiveTracking2",
          "type": "TEXT",
          "required": false,
          "position": 33,
          "choicesJson": null
        },
        {
          "key": "pathaccnumber2",
          "label": "PathAccNumber",
          "type": "TEXT",
          "required": false,
          "position": 34,
          "choicesJson": null
        },
        {
          "key": "otheraccnumber",
          "label": "OtherAccNumber",
          "type": "TEXT",
          "required": false,
          "position": 35,
          "choicesJson": null
        },
        {
          "key": "block_received2",
          "label": "Block_ Received2",
          "type": "TEXT",
          "required": false,
          "position": 36,
          "choicesJson": null
        },
        {
          "key": "stainedslide_received2",
          "label": "StainedSlide_Received2",
          "type": "TEXT",
          "required": false,
          "position": 37,
          "choicesJson": null
        },
        {
          "key": "unstainedslide_received2",
          "label": "UnstainedSlide_Received2",
          "type": "TEXT",
          "required": false,
          "position": 38,
          "choicesJson": null
        },
        {
          "key": "return_needed2",
          "label": "Return_needed?",
          "type": "BOOLEAN",
          "required": false,
          "position": 39,
          "choicesJson": null
        },
        {
          "key": "returndate2",
          "label": "ReturnDate2",
          "type": "DATE",
          "required": false,
          "position": 40,
          "choicesJson": null
        },
        {
          "key": "return_tracking2",
          "label": "ReturnTracking2",
          "type": "TEXT",
          "required": false,
          "position": 41,
          "choicesJson": null
        },
        {
          "key": "thirdtime_getsample",
          "label": "3rd_Time_Receive",
          "type": "BOOLEAN",
          "required": false,
          "position": 42,
          "choicesJson": null
        },
        {
          "key": "follow_up_needed3",
          "label": "Follow up needed?",
          "type": "BOOLEAN",
          "required": false,
          "position": 43,
          "choicesJson": null
        },
        {
          "key": "collection_note3",
          "label": "FollowUp_Note",
          "type": "TEXT",
          "required": false,
          "position": 44,
          "choicesJson": null
        },
        {
          "key": "samefacilityasbefore2",
          "label": "SameFacilityAsBefore?",
          "type": "BOOLEAN",
          "required": false,
          "position": 45,
          "choicesJson": null
        },
        {
          "key": "facility_name3",
          "label": "Facility_Name3",
          "type": "TEXT",
          "required": false,
          "position": 46,
          "choicesJson": null
        },
        {
          "key": "facility_city3",
          "label": "Facility_City3",
          "type": "TEXT",
          "required": false,
          "position": 47,
          "choicesJson": null
        },
        {
          "key": "facility_state3",
          "label": "Facility_State3",
          "type": "TEXT",
          "required": false,
          "position": 48,
          "choicesJson": null
        },
        {
          "key": "receivedate3",
          "label": "ReceiveDate3",
          "type": "DATE",
          "required": false,
          "position": 49,
          "choicesJson": null
        },
        {
          "key": "shipmethod3",
          "label": "ShipMethod3",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 50,
          "choicesJson": [
            {
              "value": "1",
              "label": "FedEx"
            },
            {
              "value": "2",
              "label": "USPS"
            },
            {
              "value": "3",
              "label": "UPS"
            },
            {
              "value": "4",
              "label": "ByPerson"
            },
            {
              "value": "5",
              "label": "Others"
            }
          ]
        },
        {
          "key": "receivetracking3",
          "label": "ReceiveTracking3",
          "type": "TEXT",
          "required": false,
          "position": 51,
          "choicesJson": null
        },
        {
          "key": "pathaccnumber3",
          "label": "PathAccNumber3",
          "type": "TEXT",
          "required": false,
          "position": 52,
          "choicesJson": null
        },
        {
          "key": "otheraccnumber3",
          "label": "OtherAccNumber",
          "type": "TEXT",
          "required": false,
          "position": 53,
          "choicesJson": null
        },
        {
          "key": "block_received3",
          "label": "Block_ Received3",
          "type": "TEXT",
          "required": false,
          "position": 54,
          "choicesJson": null
        },
        {
          "key": "stainedslide_received3",
          "label": "StainedSlide_Received3",
          "type": "TEXT",
          "required": false,
          "position": 55,
          "choicesJson": null
        },
        {
          "key": "unstainedslide_received3",
          "label": "UnstainedSlide_Received3",
          "type": "TEXT",
          "required": false,
          "position": 56,
          "choicesJson": null
        },
        {
          "key": "return_needed3",
          "label": "Return_needed?",
          "type": "BOOLEAN",
          "required": false,
          "position": 57,
          "choicesJson": null
        },
        {
          "key": "returndate3",
          "label": "ReturnDate3",
          "type": "DATE",
          "required": false,
          "position": 58,
          "choicesJson": null
        },
        {
          "key": "returntracking3",
          "label": "ReturnTracking3",
          "type": "TEXT",
          "required": false,
          "position": 59,
          "choicesJson": null
        },
        {
          "key": "id_shipping_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 60,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "pathology_review",
      "displayName": "Pathology Review",
      "fields": [
        {
          "key": "tumor_origin",
          "label": "Tumor_Origin",
          "type": "SINGLE_SELECT",
          "required": true,
          "position": 0,
          "choicesJson": [
            {
              "value": "1",
              "label": "Breast"
            },
            {
              "value": "2",
              "label": "Prostate"
            },
            {
              "value": "3",
              "label": "Colorectum"
            },
            {
              "value": "4",
              "label": "Lung"
            },
            {
              "value": "5",
              "label": "Others"
            }
          ]
        },
        {
          "key": "specify_other_origin",
          "label": "Specify_Other_Origin",
          "type": "TEXT",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "tumor_location",
          "label": "Location_Breast_Prostate",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 2,
          "choicesJson": [
            {
              "value": "1",
              "label": "Left"
            },
            {
              "value": "2",
              "label": "Right"
            },
            {
              "value": "3",
              "label": "Bilateral"
            },
            {
              "value": "4",
              "label": "Multiple"
            },
            {
              "value": "5",
              "label": "Unclear"
            }
          ]
        },
        {
          "key": "tumor_location_colorectum",
          "label": "Location_Colorectum",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 3,
          "choicesJson": [
            {
              "value": "1",
              "label": "Appendix"
            },
            {
              "value": "2",
              "label": "Cecum"
            },
            {
              "value": "3",
              "label": "Ascending"
            },
            {
              "value": "4",
              "label": "Hepatic Flexure"
            },
            {
              "value": "5",
              "label": "Transverse"
            },
            {
              "value": "6",
              "label": "Splenic Flexure"
            },
            {
              "value": "7",
              "label": "Descending"
            },
            {
              "value": "8",
              "label": "Sigmoid"
            },
            {
              "value": "9",
              "label": "Rectum"
            },
            {
              "value": "10",
              "label": "Anus"
            },
            {
              "value": "11",
              "label": "Left"
            },
            {
              "value": "12",
              "label": "Right"
            },
            {
              "value": "13",
              "label": "Unclear"
            }
          ]
        },
        {
          "key": "tumor_location_lung",
          "label": "Location_Lung",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 4,
          "choicesJson": [
            {
              "value": "1",
              "label": "Right Upper Lobe"
            },
            {
              "value": "2",
              "label": "Right Middle Lobe"
            },
            {
              "value": "3",
              "label": "Right Lower Lobe"
            },
            {
              "value": "4",
              "label": "Left Upper Lobe"
            },
            {
              "value": "5",
              "label": "Left Lower Lobe"
            },
            {
              "value": "6",
              "label": "Right Bronchus"
            },
            {
              "value": "7",
              "label": "Left Bronchus"
            },
            {
              "value": "8",
              "label": "Right"
            },
            {
              "value": "9",
              "label": "Left"
            },
            {
              "value": "10",
              "label": "Unclear"
            },
            {
              "value": "11",
              "label": "Others (specify it)"
            }
          ]
        },
        {
          "key": "other_location_lung",
          "label": "Other location_lung",
          "type": "TEXT",
          "required": false,
          "position": 5,
          "choicesJson": null
        },
        {
          "key": "specify_other_location",
          "label": "Specify_Other_Location",
          "type": "TEXT",
          "required": false,
          "position": 6,
          "choicesJson": null
        },
        {
          "key": "date_surgery",
          "label": "Date_Surgery",
          "type": "DATE",
          "required": false,
          "position": 7,
          "choicesJson": null
        },
        {
          "key": "age_at_surgery",
          "label": "Age at Surgery",
          "type": "TEXT",
          "required": false,
          "position": 8,
          "choicesJson": null,
          "note": "Imported from REDCap calc field; calculation logic is not migrated."
        },
        {
          "key": "sex",
          "label": "sex",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 9,
          "choicesJson": [
            {
              "value": "0",
              "label": "Female"
            },
            {
              "value": "1",
              "label": "Male"
            },
            {
              "value": "2",
              "label": "Other"
            },
            {
              "value": "3",
              "label": "Prefer not to say"
            }
          ]
        },
        {
          "key": "pathol_acc_no",
          "label": "Pathol_Acc_No",
          "type": "TEXT",
          "required": true,
          "position": 10,
          "choicesJson": null
        },
        {
          "key": "other_acc_no",
          "label": "Other_Acc_No",
          "type": "TEXT",
          "required": false,
          "position": 11,
          "choicesJson": null
        },
        {
          "key": "block_tumor",
          "label": "BlockNum_Tumor",
          "type": "TEXT",
          "required": false,
          "position": 12,
          "choicesJson": null
        },
        {
          "key": "block_normal",
          "label": "BlockNum_Normal",
          "type": "TEXT",
          "required": false,
          "position": 13,
          "choicesJson": null
        },
        {
          "key": "block_metastatic",
          "label": "BlockNum_Metastatic",
          "type": "TEXT",
          "required": false,
          "position": 14,
          "choicesJson": null
        },
        {
          "key": "block_precancerous",
          "label": "BlockNum_Precancerous",
          "type": "TEXT",
          "required": false,
          "position": 15,
          "choicesJson": null
        },
        {
          "key": "invitrosize1",
          "label": "InvitroSize1",
          "type": "TEXT",
          "required": false,
          "position": 16,
          "choicesJson": null
        },
        {
          "key": "invitrosize2",
          "label": "InvitroSize2",
          "type": "TEXT",
          "required": false,
          "position": 17,
          "choicesJson": null
        },
        {
          "key": "invitrosize3",
          "label": "InvitroSize3",
          "type": "TEXT",
          "required": false,
          "position": 18,
          "choicesJson": null
        },
        {
          "key": "perineuralinvasion",
          "label": "PerineuralInvasion",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 19,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            },
            {
              "value": "2",
              "label": "N/A"
            }
          ]
        },
        {
          "key": "vascular_invasion",
          "label": "Vascular invasion present",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 20,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            },
            {
              "value": "2",
              "label": "N/A"
            }
          ]
        },
        {
          "key": "surgical_margin_cancer_pre",
          "label": "Surgical margin cancer present",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 21,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            },
            {
              "value": "2",
              "label": "N/A"
            }
          ]
        },
        {
          "key": "clin_diagn_breast",
          "label": "Clin_Diagn_Breast",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 22,
          "choicesJson": [
            {
              "value": "1",
              "label": "Noninvasive carcinoma (NOS)"
            },
            {
              "value": "2",
              "label": "Ductal carcinoma in situ"
            },
            {
              "value": "3",
              "label": "Lobular carcinoma in situ"
            },
            {
              "value": "4",
              "label": "Paget disease without invasive carcinoma"
            },
            {
              "value": "5",
              "label": "Invasive carcinoma (NOS)"
            },
            {
              "value": "6",
              "label": "Invasive ductal carcinoma"
            },
            {
              "value": "7",
              "label": "IDC with an extensive intraductal component"
            },
            {
              "value": "8",
              "label": "IDC with Paget disease"
            },
            {
              "value": "9",
              "label": "Invasive lobular"
            },
            {
              "value": "10",
              "label": "Mucinous"
            },
            {
              "value": "11",
              "label": "Medullary"
            },
            {
              "value": "12",
              "label": "Papillary"
            },
            {
              "value": "13",
              "label": "Tubular"
            },
            {
              "value": "14",
              "label": "Adenoid cystic"
            },
            {
              "value": "15",
              "label": "Secretory (juvenile)"
            },
            {
              "value": "16",
              "label": "Apocrine"
            },
            {
              "value": "17",
              "label": "Cribriform"
            },
            {
              "value": "18",
              "label": "Carcinoma with squamous metaplasia"
            },
            {
              "value": "19",
              "label": "Carcinoma with spindle cell metaplasia"
            },
            {
              "value": "20",
              "label": "Carcinoma with cartilaginous/osseous metaplasia"
            },
            {
              "value": "21",
              "label": "Carcinoma with metaplasia, mixed type"
            },
            {
              "value": "22",
              "label": "Other(s) (specify)"
            },
            {
              "value": "23",
              "label": "Not assessable"
            },
            {
              "value": "24",
              "label": "No cancer tissue"
            },
            {
              "value": "25",
              "label": "IDC+ILC (50 -90% each component)"
            }
          ]
        },
        {
          "key": "lab_diagn_breast",
          "label": "Lab_Diagn_Breast",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 23,
          "choicesJson": [
            {
              "value": "1",
              "label": "Noninvasive carcinoma (NOS)"
            },
            {
              "value": "2",
              "label": "Ductal carcinoma in situ"
            },
            {
              "value": "3",
              "label": "Lobular carcinoma in situ"
            },
            {
              "value": "4",
              "label": "Paget disease without invasive carcinoma"
            },
            {
              "value": "5",
              "label": "Invasive carcinoma (NOS)"
            },
            {
              "value": "6",
              "label": "Invasive ductal carcinoma"
            },
            {
              "value": "7",
              "label": "IDC with an extensive intraductal component"
            },
            {
              "value": "8",
              "label": "IDC with Paget disease"
            },
            {
              "value": "9",
              "label": "Invasive lobular"
            },
            {
              "value": "10",
              "label": "Mucinous"
            },
            {
              "value": "11",
              "label": "Medullary"
            },
            {
              "value": "12",
              "label": "Papillary"
            },
            {
              "value": "13",
              "label": "Tubular"
            },
            {
              "value": "14",
              "label": "Adenoid cystic"
            },
            {
              "value": "15",
              "label": "Secretory (juvenile)"
            },
            {
              "value": "16",
              "label": "Apocrine"
            },
            {
              "value": "17",
              "label": "Cribriform"
            },
            {
              "value": "18",
              "label": "Carcinoma with squamous metaplasia"
            },
            {
              "value": "19",
              "label": "Carcinoma with spindle cell metaplasia"
            },
            {
              "value": "20",
              "label": "Carcinoma with cartilaginous/osseous metaplasia"
            },
            {
              "value": "21",
              "label": "Carcinoma with metaplasia, mixed type"
            },
            {
              "value": "22",
              "label": "Other(s) (specify)"
            },
            {
              "value": "23",
              "label": "Not assessable"
            },
            {
              "value": "24",
              "label": "No cancer tissue"
            },
            {
              "value": "25",
              "label": "IDC+ILC (50 -90% each component)"
            }
          ]
        },
        {
          "key": "if_ilc_subtype",
          "label": "ILC_Subtype",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 24,
          "choicesJson": [
            {
              "value": "901",
              "label": "classical ILC"
            },
            {
              "value": "902",
              "label": "solid ILC"
            },
            {
              "value": "903",
              "label": "pleomorphic ILC"
            },
            {
              "value": "904",
              "label": "alveolar ILC"
            },
            {
              "value": "905",
              "label": "tubulolobular ILC"
            },
            {
              "value": "906",
              "label": "mixed ILC"
            },
            {
              "value": "907",
              "label": "signet ring cell ILC"
            },
            {
              "value": "908",
              "label": "others"
            }
          ]
        },
        {
          "key": "specify_if_other_type_br",
          "label": "Specify_If_Other_Type_Br",
          "type": "TEXT",
          "required": false,
          "position": 25,
          "choicesJson": null
        },
        {
          "key": "clin_grade_breast",
          "label": "Clin_Grade_Breast",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 26,
          "choicesJson": [
            {
              "value": "1",
              "label": "1"
            },
            {
              "value": "2",
              "label": "2"
            },
            {
              "value": "3",
              "label": "3"
            },
            {
              "value": "4",
              "label": "1~2"
            },
            {
              "value": "5",
              "label": "2~3"
            },
            {
              "value": "6",
              "label": "N/A"
            }
          ]
        },
        {
          "key": "lab_grade_breast",
          "label": "Lab_Grade_Breast",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 27,
          "choicesJson": [
            {
              "value": "1",
              "label": "1"
            },
            {
              "value": "2",
              "label": "2"
            },
            {
              "value": "3",
              "label": "3"
            },
            {
              "value": "4",
              "label": "N/A"
            }
          ]
        },
        {
          "key": "estrogen_receptor",
          "label": "Estrogen Receptor",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 28,
          "choicesJson": [
            {
              "value": "0",
              "label": "negative"
            },
            {
              "value": "1",
              "label": "week (<1%)"
            },
            {
              "value": "2",
              "label": "positive (>=1%)"
            },
            {
              "value": "3",
              "label": "N/A"
            }
          ]
        },
        {
          "key": "progesterone_receptor",
          "label": "Progesterone Receptor",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 29,
          "choicesJson": [
            {
              "value": "0",
              "label": "negative (0~2)"
            },
            {
              "value": "1",
              "label": "week (3~4)"
            },
            {
              "value": "2",
              "label": "intermediate (5~6)"
            },
            {
              "value": "3",
              "label": "strong (7~8)"
            },
            {
              "value": "4",
              "label": "N/A"
            }
          ]
        },
        {
          "key": "her2_immunohistochemistry",
          "label": "HER2_Immunohistochemistry",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 30,
          "choicesJson": [
            {
              "value": "0",
              "label": "0"
            },
            {
              "value": "1",
              "label": "1 (1~9% cells positivity)"
            },
            {
              "value": "2",
              "label": "2 (10-30% cells positivity)"
            },
            {
              "value": "3",
              "label": "3 (>30% cells positivity with strong color)"
            },
            {
              "value": "4",
              "label": "N/A"
            }
          ]
        },
        {
          "key": "her2_fish",
          "label": "HER2_FISH",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 31,
          "choicesJson": [
            {
              "value": "0",
              "label": "0 (Non-Amplified, <1.8)"
            },
            {
              "value": "1",
              "label": "1 (Amplified, >2.2)"
            },
            {
              "value": "2",
              "label": "2 (Borderline, 1.8~2.2)"
            },
            {
              "value": "3",
              "label": "N/A"
            }
          ]
        },
        {
          "key": "bc_molecularsubtype",
          "label": "BC_MolecularSubtype",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 32,
          "choicesJson": [
            {
              "value": "1",
              "label": "Luminal A"
            },
            {
              "value": "2",
              "label": "Luminal B"
            },
            {
              "value": "3",
              "label": "HER2"
            },
            {
              "value": "4",
              "label": "Triple Negative"
            },
            {
              "value": "5",
              "label": "N/A"
            }
          ]
        },
        {
          "key": "ki_67",
          "label": "Ki-67",
          "type": "TEXT",
          "required": false,
          "position": 33,
          "choicesJson": null
        },
        {
          "key": "p53_ihc",
          "label": "p53_IHC",
          "type": "TEXT",
          "required": false,
          "position": 34,
          "choicesJson": null
        },
        {
          "key": "dna_index",
          "label": "DNA Index",
          "type": "TEXT",
          "required": false,
          "position": 35,
          "choicesJson": null
        },
        {
          "key": "bc_precancerous",
          "label": "BC_Precancerous",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 36,
          "choicesJson": [
            {
              "value": "1",
              "label": "Not seen"
            },
            {
              "value": "2",
              "label": "DCIS"
            },
            {
              "value": "3",
              "label": "LCIS"
            },
            {
              "value": "4",
              "label": "DCIS+LCIS"
            }
          ]
        }
      ]
    },
    {
      "key": "tma_information",
      "displayName": "Tma Information",
      "fields": [
        {
          "key": "another_accnumber",
          "label": "Another_AccNumber?",
          "type": "BOOLEAN",
          "required": false,
          "position": 0,
          "choicesJson": null
        },
        {
          "key": "tma_ca_pos3",
          "label": "TMA_Ca_pos3",
          "type": "TEXT",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "tma_ca_pos4",
          "label": "TMA_Ca_pos4",
          "type": "TEXT",
          "required": false,
          "position": 2,
          "choicesJson": null
        },
        {
          "key": "tma_nor_pos3",
          "label": "TMA_Nor_pos3",
          "type": "TEXT",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "tma_nor_pos4",
          "label": "TMA_Nor_pos4",
          "type": "TEXT",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "tma_preca_pos2",
          "label": "TMA_ PreCa_pos2",
          "type": "TEXT",
          "required": false,
          "position": 5,
          "choicesJson": null
        },
        {
          "key": "tma_metastatic_pos2",
          "label": "TMA Metastatic_pos2",
          "type": "TEXT",
          "required": false,
          "position": 6,
          "choicesJson": null
        },
        {
          "key": "tma_information_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 7,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "slide_tracking",
      "displayName": "Slide Tracking",
      "fields": [
        {
          "key": "pulling_date1",
          "label": "Pulling_Date1",
          "type": "DATE",
          "required": false,
          "position": 0,
          "choicesJson": null
        },
        {
          "key": "forwhoseproject",
          "label": "ForWhoseProject1",
          "type": "TEXT",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "whichslidepulled1",
          "label": "WhichSlidePulled1",
          "type": "TEXT",
          "required": false,
          "position": 2,
          "choicesJson": null
        },
        {
          "key": "pulled_quant1",
          "label": "Pulled_Quant1",
          "type": "TEXT",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "slide_tracking_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 4,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    }
  ]
} as TClinicalTemplate;
