// AUTO-GENERATED by apps/web/modules/clinical/onboarding/scripts/convert-redcap-sql.ts
// Source: redcap/redcap_v15.8.4/Resources/sql/create_demo_db14.sql
// Do not edit by hand — regenerate by running the converter.
import type { TClinicalTemplate } from "../template-types";

export const dashboardsSmartChartsTemplate: TClinicalTemplate = {
  "key": "dashboards_smart_charts",
  "name": "Project Dashboards, Smart Functions, Smart Tables, & Smart Charts",
  "description": "Demonstrates REDCap dashboards / smart functions / smart charts. Those features are not available in Continium; the protocol skeleton is created without them.",
  "purpose": "practice",
  "source": {
    "redcapDemo": "Project Dashboards, Smart Functions, Smart Tables, & Smart Charts",
    "sourceFile": "redcap/redcap_v15.8.4/Resources/sql/create_demo_db14.sql"
  },
  "unsupportedFeatures": [
    "REDCap project dashboards",
    "Smart Functions / Smart Tables / Smart Charts"
  ],
  "arms": [
    {
      "name": "Arm 1",
      "position": 0,
      "events": [
        {
          "name": "Event 1",
          "position": 0,
          "dayOffset": 0,
          "windowDays": null,
          "instrumentBindings": [
            {
              "instrumentKey": "default",
              "required": true,
              "repeating": false
            }
          ]
        }
      ]
    }
  ],
  "instruments": [
    {
      "key": "default",
      "displayName": "Default Form",
      "fields": []
    }
  ]
} as TClinicalTemplate;
