// AUTO-GENERATED by apps/web/modules/clinical/onboarding/scripts/convert-redcap-sql.ts
// Source: redcap/redcap_v15.8.4/Resources/sql/create_demo_db13.sql
// Do not edit by hand — regenerate by running the converter.
import type { TClinicalTemplate } from "../template-types";

export const fieldEmbeddingTemplate: TClinicalTemplate = {
  "key": "field_embedding",
  "name": "Field Embedding Example Project",
  "description": "Demonstrates REDCap-specific field embedding. Continium does not yet support field embedding; fields are created as plain inputs.",
  "purpose": "practice",
  "source": {
    "redcapDemo": "Field Embedding Example Project",
    "sourceFile": "redcap/redcap_v15.8.4/Resources/sql/create_demo_db13.sql"
  },
  "unsupportedFeatures": [
    "Field embedding"
  ],
  "arms": [
    {
      "name": "Arm 1",
      "position": 0,
      "events": [
        {
          "name": "Event 1",
          "position": 0,
          "dayOffset": 0,
          "windowDays": null,
          "instrumentBindings": [
            {
              "instrumentKey": "default",
              "required": true,
              "repeating": false
            }
          ]
        }
      ]
    }
  ],
  "instruments": [
    {
      "key": "default",
      "displayName": "Default Form",
      "fields": []
    }
  ]
} as TClinicalTemplate;
