// AUTO-GENERATED by apps/web/modules/clinical/onboarding/scripts/convert-redcap-sql.ts
// Do not edit by hand — regenerate by running the converter.
import type { TClinicalTemplate } from "../template-types";
import { classicDatabaseTemplate } from "./classic_database";
import { longitudinal2ArmsTemplate } from "./longitudinal_2_arms";
import { singleSurveyTemplate } from "./single_survey";
import { longitudinal1ArmTemplate } from "./longitudinal_1_arm";
import { basicDemographyTemplate } from "./basic_demography";
import { projectTrackingTemplate } from "./project_tracking";
import { randomizedClinicalTrialTemplate } from "./randomized_clinical_trial";
import { cancerTissueBiobankTemplate } from "./cancer_tissue_biobank";
import { multipleSurveysClassicTemplate } from "./multiple_surveys_classic";
import { multipleSurveysLongitudinalTemplate } from "./multiple_surveys_longitudinal";
import { pipingExampleTemplate } from "./piping_example";
import { repeatingInstrumentsTemplate } from "./repeating_instruments";
import { fieldEmbeddingTemplate } from "./field_embedding";
import { dashboardsSmartChartsTemplate } from "./dashboards_smart_charts";
import { mycapExampleTemplate } from "./mycap_example";

export const clinicalTemplates: TClinicalTemplate[] = [
  classicDatabaseTemplate,
  longitudinal2ArmsTemplate,
  singleSurveyTemplate,
  longitudinal1ArmTemplate,
  basicDemographyTemplate,
  projectTrackingTemplate,
  randomizedClinicalTrialTemplate,
  cancerTissueBiobankTemplate,
  multipleSurveysClassicTemplate,
  multipleSurveysLongitudinalTemplate,
  pipingExampleTemplate,
  repeatingInstrumentsTemplate,
  fieldEmbeddingTemplate,
  dashboardsSmartChartsTemplate,
  mycapExampleTemplate,
];

export const clinicalTemplateByKey: Record<string, TClinicalTemplate> = Object.fromEntries(
  clinicalTemplates.map((template) => [template.key, template]),
);

export const getClinicalTemplate = (key: string): TClinicalTemplate | undefined =>
  clinicalTemplateByKey[key];

export const listClinicalTemplates = (): TClinicalTemplate[] => clinicalTemplates;
