// AUTO-GENERATED by apps/web/modules/clinical/onboarding/scripts/convert-redcap-sql.ts
// Source: redcap/redcap_v15.8.4/Resources/sql/create_demo_db4.sql
// Do not edit by hand — regenerate by running the converter.
import type { TClinicalTemplate } from "../template-types";

export const longitudinal1ArmTemplate: TClinicalTemplate = {
  "key": "longitudinal_1_arm",
  "name": "Longitudinal Database (1 arm)",
  "description": "One-arm longitudinal study with baseline, follow-ups, and final visit. Mirrors the canonical observational protocol.",
  "purpose": "research",
  "source": {
    "redcapDemo": "Longitudinal Database (1 arm)",
    "sourceFile": "redcap/redcap_v15.8.4/Resources/sql/create_demo_db4.sql"
  },
  "arms": [
    {
      "name": "Drug A",
      "position": 0,
      "events": [
        {
          "name": "Enrollment",
          "position": 0,
          "dayOffset": 0,
          "windowDays": null,
          "instrumentBindings": [
            {
              "instrumentKey": "baseline_data",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "demographics",
              "required": true,
              "repeating": false
            }
          ]
        },
        {
          "name": "Dose 1",
          "position": 1,
          "dayOffset": 1,
          "windowDays": null,
          "instrumentBindings": [
            {
              "instrumentKey": "patient_morale_questionnaire",
              "required": true,
              "repeating": false
            }
          ]
        },
        {
          "name": "Visit 1",
          "position": 2,
          "dayOffset": 3,
          "windowDays": null,
          "instrumentBindings": [
            {
              "instrumentKey": "patient_morale_questionnaire",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "visit_blood_workup",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "visit_lab_data",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "visit_observed_behavior",
              "required": true,
              "repeating": false
            }
          ]
        },
        {
          "name": "Dose 2",
          "position": 3,
          "dayOffset": 8,
          "windowDays": null,
          "instrumentBindings": [
            {
              "instrumentKey": "patient_morale_questionnaire",
              "required": true,
              "repeating": false
            }
          ]
        },
        {
          "name": "Visit 2",
          "position": 4,
          "dayOffset": 10,
          "windowDays": null,
          "instrumentBindings": [
            {
              "instrumentKey": "patient_morale_questionnaire",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "visit_blood_workup",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "visit_lab_data",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "visit_observed_behavior",
              "required": true,
              "repeating": false
            }
          ]
        },
        {
          "name": "Dose 3",
          "position": 5,
          "dayOffset": 15,
          "windowDays": null,
          "instrumentBindings": [
            {
              "instrumentKey": "patient_morale_questionnaire",
              "required": true,
              "repeating": false
            }
          ]
        },
        {
          "name": "Visit 3",
          "position": 6,
          "dayOffset": 17,
          "windowDays": null,
          "instrumentBindings": [
            {
              "instrumentKey": "patient_morale_questionnaire",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "visit_blood_workup",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "visit_lab_data",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "visit_observed_behavior",
              "required": true,
              "repeating": false
            }
          ]
        },
        {
          "name": "Final visit",
          "position": 7,
          "dayOffset": 30,
          "windowDays": null,
          "instrumentBindings": [
            {
              "instrumentKey": "completion_data",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "completion_project_questionnaire",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "patient_morale_questionnaire",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "visit_blood_workup",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "visit_observed_behavior",
              "required": true,
              "repeating": false
            }
          ]
        }
      ]
    }
  ],
  "instruments": [
    {
      "key": "demographics",
      "displayName": "Demographics",
      "fields": [
        {
          "key": "study_id",
          "label": "Study ID",
          "type": "TEXT",
          "required": false,
          "position": 0,
          "choicesJson": null
        },
        {
          "key": "date_enrolled",
          "label": "Date subject signed consent",
          "type": "DATE",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "patient_document",
          "label": "Upload the patient''s consent form",
          "type": "TEXT",
          "required": false,
          "position": 2,
          "choicesJson": null,
          "note": "Imported from REDCap file-upload field; file uploads are not yet supported."
        },
        {
          "key": "first_name",
          "label": "First Name",
          "type": "TEXT",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "last_name",
          "label": "Last Name",
          "type": "TEXT",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "address",
          "label": "Street, City, State, ZIP",
          "type": "TEXT",
          "required": false,
          "position": 5,
          "choicesJson": null
        },
        {
          "key": "telephone_1",
          "label": "Phone number",
          "type": "TEXT",
          "required": false,
          "position": 6,
          "choicesJson": null
        },
        {
          "key": "email",
          "label": "E-mail",
          "type": "TEXT",
          "required": false,
          "position": 7,
          "choicesJson": null
        },
        {
          "key": "dob",
          "label": "Date of birth",
          "type": "DATE",
          "required": false,
          "position": 8,
          "choicesJson": null
        },
        {
          "key": "age",
          "label": "Age (years)",
          "type": "TEXT",
          "required": false,
          "position": 9,
          "choicesJson": null,
          "note": "Imported from REDCap calc field; calculation logic is not migrated."
        },
        {
          "key": "ethnicity",
          "label": "Ethnicity",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 10,
          "choicesJson": [
            {
              "value": "0",
              "label": "Hispanic or Latino"
            },
            {
              "value": "1",
              "label": "NOT Hispanic or Latino"
            },
            {
              "value": "2",
              "label": "Unknown / Not Reported"
            }
          ]
        },
        {
          "key": "race",
          "label": "Race",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 11,
          "choicesJson": [
            {
              "value": "0",
              "label": "American Indian/Alaska Native"
            },
            {
              "value": "1",
              "label": "Asian"
            },
            {
              "value": "2",
              "label": "Native Hawaiian or Other Pacific Islander"
            },
            {
              "value": "3",
              "label": "Black or African American"
            },
            {
              "value": "4",
              "label": "White"
            },
            {
              "value": "5",
              "label": "More Than One Race"
            },
            {
              "value": "6",
              "label": "Unknown / Not Reported"
            }
          ]
        },
        {
          "key": "sex",
          "label": "sex",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 12,
          "choicesJson": [
            {
              "value": "0",
              "label": "Female"
            },
            {
              "value": "1",
              "label": "Male"
            },
            {
              "value": "2",
              "label": "Other"
            },
            {
              "value": "3",
              "label": "Prefer not to say"
            }
          ]
        },
        {
          "key": "given_birth",
          "label": "Has the patient given birth before?",
          "type": "BOOLEAN",
          "required": false,
          "position": 13,
          "choicesJson": null
        },
        {
          "key": "num_children",
          "label": "How many times has the patient given birth?",
          "type": "TEXT",
          "required": false,
          "position": 14,
          "choicesJson": null
        },
        {
          "key": "gym",
          "label": "Gym (Weight Training)",
          "type": "MULTI_SELECT",
          "required": false,
          "position": 15,
          "choicesJson": [
            {
              "value": "0",
              "label": "Monday"
            },
            {
              "value": "1",
              "label": "Tuesday"
            },
            {
              "value": "2",
              "label": "Wednesday"
            },
            {
              "value": "3",
              "label": "Thursday"
            },
            {
              "value": "4",
              "label": "Friday"
            }
          ]
        },
        {
          "key": "aerobics",
          "label": "Aerobics",
          "type": "MULTI_SELECT",
          "required": false,
          "position": 16,
          "choicesJson": [
            {
              "value": "0",
              "label": "Monday"
            },
            {
              "value": "1",
              "label": "Tuesday"
            },
            {
              "value": "2",
              "label": "Wednesday"
            },
            {
              "value": "3",
              "label": "Thursday"
            },
            {
              "value": "4",
              "label": "Friday"
            }
          ]
        },
        {
          "key": "eat",
          "label": "Eat Out (Dinner/Lunch)",
          "type": "MULTI_SELECT",
          "required": false,
          "position": 17,
          "choicesJson": [
            {
              "value": "0",
              "label": "Monday"
            },
            {
              "value": "1",
              "label": "Tuesday"
            },
            {
              "value": "2",
              "label": "Wednesday"
            },
            {
              "value": "3",
              "label": "Thursday"
            },
            {
              "value": "4",
              "label": "Friday"
            }
          ]
        },
        {
          "key": "drink",
          "label": "Drink (Alcoholic Beverages)",
          "type": "MULTI_SELECT",
          "required": false,
          "position": 18,
          "choicesJson": [
            {
              "value": "0",
              "label": "Monday"
            },
            {
              "value": "1",
              "label": "Tuesday"
            },
            {
              "value": "2",
              "label": "Wednesday"
            },
            {
              "value": "3",
              "label": "Thursday"
            },
            {
              "value": "4",
              "label": "Friday"
            }
          ]
        },
        {
          "key": "specify_mood",
          "label": "Specify the patient''s mood",
          "type": "NUMBER",
          "required": false,
          "position": 19,
          "choicesJson": null,
          "note": "Imported from REDCap slider field; rendered as a numeric input."
        },
        {
          "key": "meds",
          "label": "Is patient taking any of the following medications? (check all that apply)",
          "type": "MULTI_SELECT",
          "required": false,
          "position": 20,
          "choicesJson": [
            {
              "value": "1",
              "label": "Lexapro"
            },
            {
              "value": "2",
              "label": "Celexa"
            },
            {
              "value": "3",
              "label": "Prozac"
            },
            {
              "value": "4",
              "label": "Paxil"
            },
            {
              "value": "5",
              "label": "Zoloft"
            }
          ]
        },
        {
          "key": "height",
          "label": "Height (cm)",
          "type": "TEXT",
          "required": false,
          "position": 21,
          "choicesJson": null
        },
        {
          "key": "weight",
          "label": "Weight (kilograms)",
          "type": "TEXT",
          "required": false,
          "position": 22,
          "choicesJson": null
        },
        {
          "key": "bmi",
          "label": "BMI",
          "type": "TEXT",
          "required": false,
          "position": 23,
          "choicesJson": null,
          "note": "Imported from REDCap calc field; calculation logic is not migrated."
        },
        {
          "key": "comments",
          "label": "Comments",
          "type": "TEXT",
          "required": false,
          "position": 24,
          "choicesJson": null
        },
        {
          "key": "demographics_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 25,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "baseline_data",
      "displayName": "Baseline Data",
      "fields": [
        {
          "key": "height2",
          "label": "Height (cm)",
          "type": "TEXT",
          "required": false,
          "position": 0,
          "choicesJson": null
        },
        {
          "key": "weight2",
          "label": "Weight (kilograms)",
          "type": "TEXT",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "bmi2",
          "label": "BMI",
          "type": "TEXT",
          "required": false,
          "position": 2,
          "choicesJson": null,
          "note": "Imported from REDCap calc field; calculation logic is not migrated."
        },
        {
          "key": "prealb_b",
          "label": "Serum Prealbumin (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "creat_b",
          "label": "Creatinine (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "npcr_b",
          "label": "Normalized Protein Catabolic Rate (g/kg/d)",
          "type": "TEXT",
          "required": false,
          "position": 5,
          "choicesJson": null
        },
        {
          "key": "chol_b",
          "label": "Cholesterol (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 6,
          "choicesJson": null
        },
        {
          "key": "transferrin_b",
          "label": "Transferrin (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 7,
          "choicesJson": null
        },
        {
          "key": "baseline_data_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 8,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "visit_lab_data",
      "displayName": "Visit Lab Data",
      "fields": [
        {
          "key": "vld1",
          "label": "Serum Prealbumin (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 0,
          "choicesJson": null
        },
        {
          "key": "vld2",
          "label": "Creatinine (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "vld3",
          "label": "Normalized Protein Catabolic Rate (g/kg/d)",
          "type": "TEXT",
          "required": false,
          "position": 2,
          "choicesJson": null
        },
        {
          "key": "vld4",
          "label": "Cholesterol (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "vld5",
          "label": "Transferrin (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "visit_lab_data_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 5,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "patient_morale_questionnaire",
      "displayName": "Patient Morale Questionnaire",
      "fields": [
        {
          "key": "pmq1",
          "label": "On average, how many pills did you take each day last week?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 0,
          "choicesJson": [
            {
              "value": "0",
              "label": "less than 5"
            },
            {
              "value": "1",
              "label": "5-10"
            },
            {
              "value": "2",
              "label": "6-15"
            },
            {
              "value": "3",
              "label": "over 15"
            }
          ]
        },
        {
          "key": "pmq2",
          "label": "Using the handout, which level of dependence do you feel you are currently at?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 1,
          "choicesJson": [
            {
              "value": "0",
              "label": "0"
            },
            {
              "value": "1",
              "label": "1"
            },
            {
              "value": "2",
              "label": "2"
            },
            {
              "value": "3",
              "label": "3"
            },
            {
              "value": "4",
              "label": "4"
            },
            {
              "value": "5",
              "label": "5"
            }
          ]
        },
        {
          "key": "pmq3",
          "label": "Would you be willing to discuss your experiences with a psychiatrist?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 2,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "pmq4",
          "label": "How open are you to further testing?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 3,
          "choicesJson": [
            {
              "value": "0",
              "label": "not open"
            },
            {
              "value": "1",
              "label": "undecided"
            },
            {
              "value": "2",
              "label": "very open"
            }
          ]
        },
        {
          "key": "patient_morale_questionnaire_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 4,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "visit_blood_workup",
      "displayName": "Visit Blood Workup",
      "fields": [
        {
          "key": "vbw1",
          "label": "Serum Prealbumin (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 0,
          "choicesJson": null
        },
        {
          "key": "vbw2",
          "label": "Creatinine (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "vbw3",
          "label": "Normalized Protein Catabolic Rate (g/kg/d)",
          "type": "TEXT",
          "required": false,
          "position": 2,
          "choicesJson": null
        },
        {
          "key": "vbw4",
          "label": "Cholesterol (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "vbw5",
          "label": "Transferrin (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "vbw6",
          "label": "Blood draw shift?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 5,
          "choicesJson": [
            {
              "value": "0",
              "label": "AM"
            },
            {
              "value": "1",
              "label": "PM"
            }
          ]
        },
        {
          "key": "vbw7",
          "label": "Blood draw by",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 6,
          "choicesJson": [
            {
              "value": "0",
              "label": "RN"
            },
            {
              "value": "1",
              "label": "LPN"
            },
            {
              "value": "2",
              "label": "nurse assistant"
            },
            {
              "value": "3",
              "label": "doctor"
            }
          ]
        },
        {
          "key": "vbw8",
          "label": "Level of patient anxiety",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 7,
          "choicesJson": [
            {
              "value": "0",
              "label": "not anxious"
            },
            {
              "value": "1",
              "label": "undecided"
            },
            {
              "value": "2",
              "label": "very anxious"
            }
          ]
        },
        {
          "key": "vbw9",
          "label": "Patient scheduled for future draws?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 8,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "visit_blood_workup_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 9,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "visit_observed_behavior",
      "displayName": "Visit Observed Behavior",
      "fields": [
        {
          "key": "vob1",
          "label": "nervous?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 0,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "vob2",
          "label": "worried?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 1,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "vob3",
          "label": "scared?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 2,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "vob4",
          "label": "fidgety?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 3,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "vob5",
          "label": "crying?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 4,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "vob6",
          "label": "screaming?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 5,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "vob7",
          "label": "other",
          "type": "TEXT",
          "required": false,
          "position": 6,
          "choicesJson": null
        },
        {
          "key": "vob8",
          "label": "nervous?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 7,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "vob9",
          "label": "worried?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 8,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "vob10",
          "label": "scared?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 9,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "vob11",
          "label": "fidgety?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 10,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "vob12",
          "label": "crying?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 11,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "vob13",
          "label": "screaming?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 12,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "vob14",
          "label": "other",
          "type": "TEXT",
          "required": false,
          "position": 13,
          "choicesJson": null
        },
        {
          "key": "visit_observed_behavior_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 14,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "completion_data",
      "displayName": "Completion Data",
      "fields": [
        {
          "key": "study_comments",
          "label": "Comments",
          "type": "TEXT",
          "required": false,
          "position": 0,
          "choicesJson": null
        },
        {
          "key": "complete_study",
          "label": "Has patient completed study?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 1,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "withdraw_date",
          "label": "Put a date if patient withdrew study",
          "type": "DATE",
          "required": false,
          "position": 2,
          "choicesJson": null
        },
        {
          "key": "date_visit_4",
          "label": "Date of last visit",
          "type": "DATE",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "alb_4",
          "label": "Serum Albumin (g/dL)",
          "type": "TEXT",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "prealb_4",
          "label": "Serum Prealbumin (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 5,
          "choicesJson": null
        },
        {
          "key": "creat_4",
          "label": "Creatinine (mg/dL)",
          "type": "DATE",
          "required": false,
          "position": 6,
          "choicesJson": null
        },
        {
          "key": "discharge_date_4",
          "label": "Date of hospital discharge",
          "type": "DATE",
          "required": false,
          "position": 7,
          "choicesJson": null
        },
        {
          "key": "discharge_summary_4",
          "label": "Discharge summary in patients binder?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 8,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "npcr_4",
          "label": "Normalized Protein Catabolic Rate (g/kg/d)",
          "type": "TEXT",
          "required": false,
          "position": 9,
          "choicesJson": null
        },
        {
          "key": "chol_4",
          "label": "Cholesterol (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 10,
          "choicesJson": null
        },
        {
          "key": "withdraw_reason",
          "label": "Reason patient withdrew from study",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 11,
          "choicesJson": [
            {
              "value": "0",
              "label": "Non-compliance"
            },
            {
              "value": "1",
              "label": "Did not wish to continue in study"
            },
            {
              "value": "2",
              "label": "Could not tolerate the supplement"
            },
            {
              "value": "3",
              "label": "Hospitalization"
            },
            {
              "value": "4",
              "label": "Other"
            }
          ]
        },
        {
          "key": "completion_data_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 12,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "completion_project_questionnaire",
      "displayName": "Completion Project Questionnaire",
      "fields": [
        {
          "key": "cpq1",
          "label": "Date of study completion",
          "type": "DATE",
          "required": false,
          "position": 0,
          "choicesJson": null
        },
        {
          "key": "cpq2",
          "label": "Transferrin (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "cpq3",
          "label": "Kt/V",
          "type": "TEXT",
          "required": false,
          "position": 2,
          "choicesJson": null
        },
        {
          "key": "cpq4",
          "label": "Dry weight (kilograms)",
          "type": "TEXT",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "cpq5",
          "label": "Number of treatments missed",
          "type": "TEXT",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "cpq6",
          "label": "How compliant was the patient in drinking the supplement?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 5,
          "choicesJson": [
            {
              "value": "0",
              "label": "100 percent"
            },
            {
              "value": "1",
              "label": "99-75 percent"
            },
            {
              "value": "2",
              "label": "74-50 percent"
            },
            {
              "value": "3",
              "label": "49-25 percent"
            },
            {
              "value": "4",
              "label": "0-24 percent"
            }
          ]
        },
        {
          "key": "cpq7",
          "label": "Was patient hospitalized since last visit?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 6,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "cpq8",
          "label": "What was the cause of hospitalization?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 7,
          "choicesJson": [
            {
              "value": "1",
              "label": "Vascular access related events"
            },
            {
              "value": "2",
              "label": "CVD events"
            },
            {
              "value": "3",
              "label": "Other"
            }
          ]
        },
        {
          "key": "cpq9",
          "label": "Date of hospital admission",
          "type": "DATE",
          "required": false,
          "position": 8,
          "choicesJson": null
        },
        {
          "key": "cpq10",
          "label": "On average, how many pills did you take each day last week?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 9,
          "choicesJson": [
            {
              "value": "0",
              "label": "less than 5"
            },
            {
              "value": "1",
              "label": "5-10"
            },
            {
              "value": "2",
              "label": "6-15"
            },
            {
              "value": "3",
              "label": "over 15"
            }
          ]
        },
        {
          "key": "cpq11",
          "label": "Using the handout, which level of dependence do you feel you are currently at?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 10,
          "choicesJson": [
            {
              "value": "0",
              "label": "0"
            },
            {
              "value": "1",
              "label": "1"
            },
            {
              "value": "2",
              "label": "2"
            },
            {
              "value": "3",
              "label": "3"
            },
            {
              "value": "4",
              "label": "4"
            },
            {
              "value": "5",
              "label": "5"
            }
          ]
        },
        {
          "key": "cpq12",
          "label": "Would you be willing to discuss your experiences with a psychiatrist?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 11,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "cpq13",
          "label": "How open are you to further testing?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 12,
          "choicesJson": [
            {
              "value": "0",
              "label": "not open"
            },
            {
              "value": "1",
              "label": "undecided"
            },
            {
              "value": "2",
              "label": "very open"
            }
          ]
        },
        {
          "key": "completion_project_questionnaire_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 13,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    }
  ]
} as TClinicalTemplate;
