// AUTO-GENERATED by apps/web/modules/clinical/onboarding/scripts/convert-redcap-sql.ts
// Source: redcap/redcap_v15.8.4/Resources/sql/create_demo_db10.sql
// Do not edit by hand — regenerate by running the converter.
import type { TClinicalTemplate } from "../template-types";

export const multipleSurveysLongitudinalTemplate: TClinicalTemplate = {
  "key": "multiple_surveys_longitudinal",
  "name": "Multiple Surveys (longitudinal)",
  "description": "Multi-instrument longitudinal study served as repeated surveys across visits.",
  "purpose": "research",
  "source": {
    "redcapDemo": "Multiple Surveys (longitudinal)",
    "sourceFile": "redcap/redcap_v15.8.4/Resources/sql/create_demo_db10.sql"
  },
  "arms": [
    {
      "name": "Arm 1",
      "position": 0,
      "events": []
    }
  ],
  "instruments": [
    {
      "key": "prescreening_survey",
      "displayName": "Prescreening Survey",
      "fields": [
        {
          "key": "participant_id",
          "label": "Participant ID",
          "type": "TEXT",
          "required": false,
          "position": 0,
          "choicesJson": null
        },
        {
          "key": "dob",
          "label": "Date of birth",
          "type": "DATE",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "email",
          "label": "E-mail address",
          "type": "TEXT",
          "required": false,
          "position": 2,
          "choicesJson": null
        },
        {
          "key": "has_diabetes",
          "label": "I currently have Type 2 Diabetes",
          "type": "BOOLEAN",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "consent",
          "label": "By checking this box, I certify that I am at least 18 years old and that I give my consent freely to participate in this study.",
          "type": "MULTI_SELECT",
          "required": false,
          "position": 4,
          "choicesJson": [
            {
              "value": "1",
              "label": "I consent"
            }
          ]
        },
        {
          "key": "prescreening_survey_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 5,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "participant_info_survey",
      "displayName": "Participant Info Survey",
      "fields": [
        {
          "key": "first_name",
          "label": "First Name",
          "type": "TEXT",
          "required": false,
          "position": 0,
          "choicesJson": null
        },
        {
          "key": "last_name",
          "label": "Last Name",
          "type": "TEXT",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "address",
          "label": "Street, City, State, ZIP",
          "type": "TEXT",
          "required": false,
          "position": 2,
          "choicesJson": null
        },
        {
          "key": "telephone_1",
          "label": "Phone number",
          "type": "TEXT",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "ethnicity",
          "label": "Ethnicity",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 4,
          "choicesJson": [
            {
              "value": "0",
              "label": "Hispanic or Latino"
            },
            {
              "value": "1",
              "label": "NOT Hispanic or Latino"
            },
            {
              "value": "2",
              "label": "Unknown / Not Reported"
            }
          ]
        },
        {
          "key": "race",
          "label": "Race",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 5,
          "choicesJson": [
            {
              "value": "0",
              "label": "American Indian/Alaska Native"
            },
            {
              "value": "1",
              "label": "Asian"
            },
            {
              "value": "2",
              "label": "Native Hawaiian or Other Pacific Islander"
            },
            {
              "value": "3",
              "label": "Black or African American"
            },
            {
              "value": "4",
              "label": "White"
            },
            {
              "value": "5",
              "label": "More Than One Race"
            },
            {
              "value": "6",
              "label": "Unknown / Not Reported"
            }
          ]
        },
        {
          "key": "sex",
          "label": "sex",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 6,
          "choicesJson": [
            {
              "value": "0",
              "label": "Female"
            },
            {
              "value": "1",
              "label": "Male"
            },
            {
              "value": "2",
              "label": "Other"
            },
            {
              "value": "3",
              "label": "Prefer not to say"
            }
          ]
        },
        {
          "key": "height",
          "label": "Height (cm)",
          "type": "TEXT",
          "required": false,
          "position": 7,
          "choicesJson": null
        },
        {
          "key": "weight",
          "label": "Weight (kilograms)",
          "type": "TEXT",
          "required": false,
          "position": 8,
          "choicesJson": null
        },
        {
          "key": "participant_info_survey_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 9,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "participant_morale_questionnaire",
      "displayName": "Participant Morale Questionnaire",
      "fields": [
        {
          "key": "pmq1",
          "label": "On average, how many pills did you take each day last week?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 0,
          "choicesJson": [
            {
              "value": "0",
              "label": "Less than 5"
            },
            {
              "value": "1",
              "label": "5-10"
            },
            {
              "value": "2",
              "label": "6-15"
            },
            {
              "value": "3",
              "label": "Over 15"
            }
          ]
        },
        {
          "key": "pmq2",
          "label": "Using the handout, which level of dependence do you feel you are currently at?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 1,
          "choicesJson": [
            {
              "value": "0",
              "label": "0"
            },
            {
              "value": "1",
              "label": "1"
            },
            {
              "value": "2",
              "label": "2"
            },
            {
              "value": "3",
              "label": "3"
            },
            {
              "value": "4",
              "label": "4"
            },
            {
              "value": "5",
              "label": "5"
            }
          ]
        },
        {
          "key": "choices",
          "label": "The choices you made",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 2,
          "choicesJson": [
            {
              "value": "1",
              "label": "Not satisfied at all"
            },
            {
              "value": "2",
              "label": "Somewhat dissatisfied"
            },
            {
              "value": "3",
              "label": "Indifferent"
            },
            {
              "value": "4",
              "label": "Somewhat satisfied"
            },
            {
              "value": "5",
              "label": "Very satisfied"
            }
          ]
        },
        {
          "key": "life",
          "label": "Your life overall",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 3,
          "choicesJson": [
            {
              "value": "1",
              "label": "Not satisfied at all"
            },
            {
              "value": "2",
              "label": "Somewhat dissatisfied"
            },
            {
              "value": "3",
              "label": "Indifferent"
            },
            {
              "value": "4",
              "label": "Somewhat satisfied"
            },
            {
              "value": "5",
              "label": "Very satisfied"
            }
          ]
        },
        {
          "key": "job",
          "label": "Your job",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 4,
          "choicesJson": [
            {
              "value": "1",
              "label": "Not satisfied at all"
            },
            {
              "value": "2",
              "label": "Somewhat dissatisfied"
            },
            {
              "value": "3",
              "label": "Indifferent"
            },
            {
              "value": "4",
              "label": "Somewhat satisfied"
            },
            {
              "value": "5",
              "label": "Very satisfied"
            }
          ]
        },
        {
          "key": "family",
          "label": "Your family life",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 5,
          "choicesJson": [
            {
              "value": "1",
              "label": "Not satisfied at all"
            },
            {
              "value": "2",
              "label": "Somewhat dissatisfied"
            },
            {
              "value": "3",
              "label": "Indifferent"
            },
            {
              "value": "4",
              "label": "Somewhat satisfied"
            },
            {
              "value": "5",
              "label": "Very satisfied"
            }
          ]
        },
        {
          "key": "participant_morale_questionnaire_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 6,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "completion_data",
      "displayName": "Completion Data",
      "fields": [
        {
          "key": "complete_study",
          "label": "Has patient completed study?",
          "type": "BOOLEAN",
          "required": false,
          "position": 0,
          "choicesJson": null
        },
        {
          "key": "withdraw_date",
          "label": "Put a date if patient withdrew study",
          "type": "DATE",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "withdraw_reason",
          "label": "Reason patient withdrew from study",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 2,
          "choicesJson": [
            {
              "value": "0",
              "label": "Non-compliance"
            },
            {
              "value": "1",
              "label": "Did not wish to continue in study"
            },
            {
              "value": "2",
              "label": "Could not tolerate the supplement"
            },
            {
              "value": "3",
              "label": "Hospitalization"
            },
            {
              "value": "4",
              "label": "Other"
            }
          ]
        },
        {
          "key": "date_visit_4",
          "label": "Date of last visit",
          "type": "DATE",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "discharge_date_4",
          "label": "Date of hospital discharge",
          "type": "DATE",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "discharge_summary_4",
          "label": "Discharge summary in patients binder?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 5,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "study_comments",
          "label": "Comments",
          "type": "TEXT",
          "required": false,
          "position": 6,
          "choicesJson": null
        },
        {
          "key": "completion_data_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 7,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    }
  ]
} as TClinicalTemplate;
