// AUTO-GENERATED by apps/web/modules/clinical/onboarding/scripts/convert-redcap-sql.ts
// Source: redcap/redcap_v15.8.4/Resources/sql/create_demo_db15.sql
// Do not edit by hand — regenerate by running the converter.
import type { TClinicalTemplate } from "../template-types";

export const mycapExampleTemplate: TClinicalTemplate = {
  "key": "mycap_example",
  "name": "MyCap Example Project",
  "description": "Mobile/MyCap-style protocol skeleton. MyCap features are not available in Continium; the protocol skeleton is created without them.",
  "purpose": "practice",
  "source": {
    "redcapDemo": "MyCap Example Project",
    "sourceFile": "redcap/redcap_v15.8.4/Resources/sql/create_demo_db15.sql"
  },
  "unsupportedFeatures": [
    "MyCap mobile features"
  ],
  "arms": [
    {
      "name": "Arm 1",
      "position": 0,
      "events": [
        {
          "name": "Event 1",
          "position": 0,
          "dayOffset": 0,
          "windowDays": null,
          "instrumentBindings": [
            {
              "instrumentKey": "default",
              "required": true,
              "repeating": false
            }
          ]
        }
      ]
    }
  ],
  "instruments": [
    {
      "key": "default",
      "displayName": "Default Form",
      "fields": []
    }
  ]
} as TClinicalTemplate;
