// AUTO-GENERATED by apps/web/modules/clinical/onboarding/scripts/convert-redcap-sql.ts
// Source: redcap/redcap_v15.8.4/Resources/sql/create_demo_db11.sql
// Do not edit by hand — regenerate by running the converter.
import type { TClinicalTemplate } from "../template-types";

export const pipingExampleTemplate: TClinicalTemplate = {
  "key": "piping_example",
  "name": "Piping Example Project",
  "description": "Demonstrates field-piping concepts. Continium does not yet support REDCap-style piping; fields are created as plain inputs.",
  "purpose": "practice",
  "source": {
    "redcapDemo": "Piping Example Project",
    "sourceFile": "redcap/redcap_v15.8.4/Resources/sql/create_demo_db11.sql"
  },
  "unsupportedFeatures": [
    "Field piping (Continium renders plain fields instead)"
  ],
  "arms": [
    {
      "name": "Arm 1",
      "position": 0,
      "events": [
        {
          "name": "Event 1",
          "position": 0,
          "dayOffset": 0,
          "windowDays": null,
          "instrumentBindings": [
            {
              "instrumentKey": "default",
              "required": true,
              "repeating": false
            }
          ]
        }
      ]
    }
  ],
  "instruments": [
    {
      "key": "default",
      "displayName": "Default Form",
      "fields": []
    }
  ]
} as TClinicalTemplate;
