// AUTO-GENERATED by apps/web/modules/clinical/onboarding/scripts/convert-redcap-sql.ts
// Source: redcap/redcap_v15.8.4/Resources/sql/create_demo_db6.sql
// Do not edit by hand — regenerate by running the converter.
import type { TClinicalTemplate } from "../template-types";

export const projectTrackingTemplate: TClinicalTemplate = {
  "key": "project_tracking",
  "name": "Project Tracking Database",
  "description": "Project tracking workspace for operational milestones (status, contacts, notes). Operational use, not clinical data capture.",
  "purpose": "operational_support",
  "source": {
    "redcapDemo": "Project Tracking Database",
    "sourceFile": "redcap/redcap_v15.8.4/Resources/sql/create_demo_db6.sql"
  },
  "arms": [
    {
      "name": "Arm 1",
      "position": 0,
      "events": [
        {
          "name": "Event 1",
          "position": 0,
          "dayOffset": 0,
          "windowDays": null,
          "instrumentBindings": [
            {
              "instrumentKey": "project",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "workflow",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "prereview_administrative",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "prereview_biostatistics",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "prereview_scientific",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "prereview_participant",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "prereview_budget",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "prereview_nursing",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "prereview_cores",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "prereview_sleep",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "prereview_nutrition",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "prereview_community",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "prereview_ctc",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "prereview_pi_response",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "post_award_administration",
              "required": true,
              "repeating": false
            }
          ]
        }
      ]
    }
  ],
  "instruments": [
    {
      "key": "project",
      "displayName": "Project",
      "fields": [
        {
          "key": "proj_id",
          "label": "Project ID",
          "type": "TEXT",
          "required": false,
          "position": 0,
          "choicesJson": null
        },
        {
          "key": "title",
          "label": "Project Title",
          "type": "TEXT",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "pi_firstname",
          "label": "PI First Name",
          "type": "TEXT",
          "required": false,
          "position": 2,
          "choicesJson": null
        },
        {
          "key": "pi_lastname",
          "label": "PI Last Name",
          "type": "TEXT",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "pi_vunetid",
          "label": "PI VUnetID",
          "type": "TEXT",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "project_type",
          "label": "Project Type",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 5,
          "choicesJson": [
            {
              "value": "1",
              "label": "Expedited"
            },
            {
              "value": "2",
              "label": "Full Committee"
            },
            {
              "value": "3",
              "label": "Industry only"
            }
          ]
        },
        {
          "key": "irb_number",
          "label": "IRB Number",
          "type": "TEXT",
          "required": false,
          "position": 6,
          "choicesJson": null
        },
        {
          "key": "amendment_status",
          "label": "Amendment?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 7,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "amendment_number",
          "label": "Amendment Number",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 8,
          "choicesJson": [
            {
              "value": "0",
              "label": "0"
            },
            {
              "value": "1",
              "label": "1"
            },
            {
              "value": "2",
              "label": "2"
            },
            {
              "value": "3",
              "label": "3"
            },
            {
              "value": "4",
              "label": "4"
            },
            {
              "value": "5",
              "label": "5"
            },
            {
              "value": "6",
              "label": "6"
            },
            {
              "value": "7",
              "label": "7"
            },
            {
              "value": "8",
              "label": "8"
            },
            {
              "value": "9",
              "label": "9"
            },
            {
              "value": "10",
              "label": "10"
            },
            {
              "value": "11",
              "label": "11"
            },
            {
              "value": "12",
              "label": "12"
            },
            {
              "value": "13",
              "label": "13"
            },
            {
              "value": "14",
              "label": "14"
            },
            {
              "value": "15",
              "label": "15"
            },
            {
              "value": "16",
              "label": "16"
            },
            {
              "value": "17",
              "label": "17"
            },
            {
              "value": "18",
              "label": "18"
            },
            {
              "value": "19",
              "label": "19"
            },
            {
              "value": "20",
              "label": "20"
            }
          ]
        },
        {
          "key": "crc_type",
          "label": "CRC Type",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 9,
          "choicesJson": [
            {
              "value": "A",
              "label": "A"
            },
            {
              "value": "B",
              "label": "B"
            },
            {
              "value": "C",
              "label": "C"
            },
            {
              "value": "D",
              "label": "D"
            }
          ]
        },
        {
          "key": "crc_webcamp_import",
          "label": "CRC WebCamp Project Import?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 10,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "crc_original_review",
          "label": "CRC Original Review?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 11,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "file_proposal",
          "label": "Research Proposal",
          "type": "TEXT",
          "required": false,
          "position": 12,
          "choicesJson": null,
          "note": "Imported from REDCap file-upload field; file uploads are not yet supported."
        },
        {
          "key": "file_budget",
          "label": "Budget",
          "type": "TEXT",
          "required": false,
          "position": 13,
          "choicesJson": null,
          "note": "Imported from REDCap file-upload field; file uploads are not yet supported."
        },
        {
          "key": "file_biosketch1",
          "label": "Biosketch(1)",
          "type": "TEXT",
          "required": false,
          "position": 14,
          "choicesJson": null,
          "note": "Imported from REDCap file-upload field; file uploads are not yet supported."
        },
        {
          "key": "file_biosketch2",
          "label": "Biosketch(2)",
          "type": "TEXT",
          "required": false,
          "position": 15,
          "choicesJson": null,
          "note": "Imported from REDCap file-upload field; file uploads are not yet supported."
        },
        {
          "key": "file_biosketch3",
          "label": "Biosketch(3)",
          "type": "TEXT",
          "required": false,
          "position": 16,
          "choicesJson": null,
          "note": "Imported from REDCap file-upload field; file uploads are not yet supported."
        },
        {
          "key": "file_crc",
          "label": "CRC Resources",
          "type": "TEXT",
          "required": false,
          "position": 17,
          "choicesJson": null,
          "note": "Imported from REDCap file-upload field; file uploads are not yet supported."
        },
        {
          "key": "file_other1",
          "label": "Other(1)",
          "type": "TEXT",
          "required": false,
          "position": 18,
          "choicesJson": null,
          "note": "Imported from REDCap file-upload field; file uploads are not yet supported."
        },
        {
          "key": "file_other2",
          "label": "Other(2)",
          "type": "TEXT",
          "required": false,
          "position": 19,
          "choicesJson": null,
          "note": "Imported from REDCap file-upload field; file uploads are not yet supported."
        },
        {
          "key": "file_other3",
          "label": "Other(3)",
          "type": "TEXT",
          "required": false,
          "position": 20,
          "choicesJson": null,
          "note": "Imported from REDCap file-upload field; file uploads are not yet supported."
        },
        {
          "key": "project_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 21,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "workflow",
      "displayName": "Workflow",
      "fields": [
        {
          "key": "date_receipt",
          "label": "Project Receipt Date",
          "type": "DATE",
          "required": false,
          "position": 0,
          "choicesJson": null
        },
        {
          "key": "date_start_preprereview",
          "label": "Pre-Pre-Review - Start Date",
          "type": "DATE",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "date_stop_preprereview",
          "label": "Pre-Pre-Review - Stop Date",
          "type": "DATE",
          "required": false,
          "position": 2,
          "choicesJson": null
        },
        {
          "key": "comments_preprereview",
          "label": "Comments - Pre-Pre-Review",
          "type": "TEXT",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "owner_prepreview",
          "label": "Owner (Liaison)",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 4,
          "choicesJson": [
            {
              "value": "0",
              "label": "Shraddha"
            },
            {
              "value": "1",
              "label": "Jennifer"
            },
            {
              "value": "2",
              "label": "Terri"
            },
            {
              "value": "3",
              "label": "Cheryl"
            },
            {
              "value": "4",
              "label": "Lynda"
            }
          ]
        },
        {
          "key": "date_start_prereview",
          "label": "Pre-Review Notification Date",
          "type": "DATE",
          "required": false,
          "position": 5,
          "choicesJson": null
        },
        {
          "key": "date_stop_prereview",
          "label": "Pre-Review Completion Date",
          "type": "DATE",
          "required": false,
          "position": 6,
          "choicesJson": null
        },
        {
          "key": "comments_prereview",
          "label": "Comments - Pre-Review",
          "type": "TEXT",
          "required": false,
          "position": 7,
          "choicesJson": null
        },
        {
          "key": "date_pi_notification",
          "label": "PI Notification Date",
          "type": "DATE",
          "required": false,
          "position": 8,
          "choicesJson": null
        },
        {
          "key": "date_pi_response",
          "label": "PI Response Date",
          "type": "DATE",
          "required": false,
          "position": 9,
          "choicesJson": null
        },
        {
          "key": "comments_pi_response",
          "label": "Comments - PI Process",
          "type": "TEXT",
          "required": false,
          "position": 10,
          "choicesJson": null
        },
        {
          "key": "file_pi_comments",
          "label": "PI response",
          "type": "TEXT",
          "required": false,
          "position": 11,
          "choicesJson": null,
          "note": "Imported from REDCap file-upload field; file uploads are not yet supported."
        },
        {
          "key": "date_agenda",
          "label": "Agenda Date",
          "type": "DATE",
          "required": false,
          "position": 12,
          "choicesJson": null
        },
        {
          "key": "rev1_name",
          "label": "Reviewer 1",
          "type": "TEXT",
          "required": false,
          "position": 13,
          "choicesJson": null
        },
        {
          "key": "rev2_name",
          "label": "Reviewer 2",
          "type": "TEXT",
          "required": false,
          "position": 14,
          "choicesJson": null
        },
        {
          "key": "rev_notification_date",
          "label": "Date - Sent to Reviewers",
          "type": "DATE",
          "required": false,
          "position": 15,
          "choicesJson": null
        },
        {
          "key": "src_notification_date",
          "label": "Date- Sent to SRC",
          "type": "DATE",
          "required": false,
          "position": 16,
          "choicesJson": null
        },
        {
          "key": "status_src_award",
          "label": "SRC Award Status",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 17,
          "choicesJson": [
            {
              "value": "0",
              "label": "Approved"
            },
            {
              "value": "1",
              "label": "Pending"
            },
            {
              "value": "2",
              "label": "Deferred (Studio)"
            },
            {
              "value": "3",
              "label": "Disapproved"
            },
            {
              "value": "4",
              "label": "Tabled"
            },
            {
              "value": "5",
              "label": "Withdrawn"
            }
          ]
        },
        {
          "key": "src_priority_score",
          "label": "SRC Priority Score",
          "type": "TEXT",
          "required": false,
          "position": 18,
          "choicesJson": null
        },
        {
          "key": "workflow_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 19,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "prereview_administrative",
      "displayName": "Prereview Administrative",
      "fields": [
        {
          "key": "needs_administrative",
          "label": "Requires Administrative?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 0,
          "choicesJson": [
            {
              "value": "0",
              "label": "Yes"
            },
            {
              "value": "1",
              "label": "No"
            }
          ]
        },
        {
          "key": "prereview_administrative",
          "label": "Notes",
          "type": "TEXT",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "prereview_administrative_doc",
          "label": "OR File<br><font size=1>(NOTE: If file will not open, then Save it to your computer and then Open it.)</font>",
          "type": "TEXT",
          "required": false,
          "position": 2,
          "choicesJson": null,
          "note": "Imported from REDCap file-upload field; file uploads are not yet supported."
        },
        {
          "key": "prereview_administrative_date_sent",
          "label": "Date Sent for pre-review",
          "type": "DATE",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "prereview_administrative_date_received",
          "label": "Date received",
          "type": "DATE",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "prereview_administrative_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 5,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "prereview_biostatistics",
      "displayName": "Prereview Biostatistics",
      "fields": [
        {
          "key": "needs_biostatistics",
          "label": "Requires Biostatistics?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 0,
          "choicesJson": [
            {
              "value": "0",
              "label": "Yes"
            },
            {
              "value": "1",
              "label": "No"
            }
          ]
        },
        {
          "key": "prereview_biostatistics",
          "label": "PI Suggestions",
          "type": "TEXT",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "prereview_biostatistics_doc",
          "label": "OR File<br><font size=1>(NOTE: If file will not open, then Save it to your computer and then Open it.)</font>",
          "type": "TEXT",
          "required": false,
          "position": 2,
          "choicesJson": null,
          "note": "Imported from REDCap file-upload field; file uploads are not yet supported."
        },
        {
          "key": "prereview_biostatistics_date_sent",
          "label": "Date Sent for pre-review",
          "type": "DATE",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "prereview_biostatistics_date_received",
          "label": "Date received",
          "type": "DATE",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "prereview_biostatistics_hours_awarded",
          "label": "Consultation Hours Awarded",
          "type": "TEXT",
          "required": false,
          "position": 5,
          "choicesJson": null
        },
        {
          "key": "prereview_biostatistics_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 6,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "prereview_scientific",
      "displayName": "Prereview Scientific",
      "fields": [
        {
          "key": "needs_scientific",
          "label": "Requires Scientific?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 0,
          "choicesJson": [
            {
              "value": "0",
              "label": "Yes"
            },
            {
              "value": "1",
              "label": "No"
            }
          ]
        },
        {
          "key": "prereview_scientific",
          "label": "PI Suggestions",
          "type": "TEXT",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "prereview_scientific_doc",
          "label": "OR File<br><font size=1>(NOTE: If file will not open, then Save it to your computer and then Open it.)</font>",
          "type": "TEXT",
          "required": false,
          "position": 2,
          "choicesJson": null,
          "note": "Imported from REDCap file-upload field; file uploads are not yet supported."
        },
        {
          "key": "prereview_scientific_date_sent",
          "label": "Date Sent for pre-review",
          "type": "DATE",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "prereview_scientific_date_received",
          "label": "Date received",
          "type": "DATE",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "prereview_scientific_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 5,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "prereview_participant",
      "displayName": "Prereview Participant",
      "fields": [
        {
          "key": "needs_participant",
          "label": "Requires Participant?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 0,
          "choicesJson": [
            {
              "value": "0",
              "label": "Yes"
            },
            {
              "value": "1",
              "label": "No"
            }
          ]
        },
        {
          "key": "prereview_participant",
          "label": "PI Suggestions",
          "type": "TEXT",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "prereview_participant_doc",
          "label": "OR File<br><font size=1>(NOTE: If file will not open, then Save it to your computer and then Open it.)</font>",
          "type": "TEXT",
          "required": false,
          "position": 2,
          "choicesJson": null,
          "note": "Imported from REDCap file-upload field; file uploads are not yet supported."
        },
        {
          "key": "prereview_participant_date_sent",
          "label": "Date Sent for pre-review",
          "type": "DATE",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "prereview_participant_date_received",
          "label": "Date received",
          "type": "DATE",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "prereview_participant_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 5,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "prereview_budget",
      "displayName": "Prereview Budget",
      "fields": [
        {
          "key": "needs_budget",
          "label": "Requires Budget?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 0,
          "choicesJson": [
            {
              "value": "0",
              "label": "Yes"
            },
            {
              "value": "1",
              "label": "No"
            }
          ]
        },
        {
          "key": "prereview_budget",
          "label": "PI Suggestions",
          "type": "TEXT",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "prereview_budget_doc",
          "label": "OR File<br><font size=1>(NOTE: If file will not open, then Save it to your computer and then Open it.)</font>",
          "type": "TEXT",
          "required": false,
          "position": 2,
          "choicesJson": null,
          "note": "Imported from REDCap file-upload field; file uploads are not yet supported."
        },
        {
          "key": "prereview_budget_date_sent",
          "label": "Date Sent for pre-review",
          "type": "DATE",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "prereview_budget_date_received",
          "label": "Date received",
          "type": "DATE",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "prereview_budget_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 5,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "prereview_nursing",
      "displayName": "Prereview Nursing",
      "fields": [
        {
          "key": "needs_nursing",
          "label": "Requires Nursing?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 0,
          "choicesJson": [
            {
              "value": "0",
              "label": "Yes"
            },
            {
              "value": "1",
              "label": "No"
            }
          ]
        },
        {
          "key": "prereview_nursing",
          "label": "PI Suggestions",
          "type": "TEXT",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "prereview_nursing_doc",
          "label": "OR File<br><font size=1>(NOTE: If file will not open, then Save it to your computer and then Open it.)</font>",
          "type": "TEXT",
          "required": false,
          "position": 2,
          "choicesJson": null,
          "note": "Imported from REDCap file-upload field; file uploads are not yet supported."
        },
        {
          "key": "prereview_nursing_date_sent",
          "label": "Date Sent for pre-review",
          "type": "DATE",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "prereview_nursing_date_received",
          "label": "Date received",
          "type": "DATE",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "prereview_nursing_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 5,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "prereview_cores",
      "displayName": "Prereview Cores",
      "fields": [
        {
          "key": "needs_cores",
          "label": "Requires Cores?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 0,
          "choicesJson": [
            {
              "value": "0",
              "label": "Yes"
            },
            {
              "value": "1",
              "label": "No"
            }
          ]
        },
        {
          "key": "prereview_cores",
          "label": "PI Suggestions",
          "type": "TEXT",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "prereview_cores_doc",
          "label": "OR File<br><font size=1>(NOTE: If file will not open, then Save it to your computer and then Open it.)</font>",
          "type": "TEXT",
          "required": false,
          "position": 2,
          "choicesJson": null,
          "note": "Imported from REDCap file-upload field; file uploads are not yet supported."
        },
        {
          "key": "prereview_cores_date_sent",
          "label": "Date Sent for pre-review",
          "type": "DATE",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "prereview_cores_date_received",
          "label": "Date received",
          "type": "DATE",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "prereview_cores_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 5,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "prereview_sleep",
      "displayName": "Prereview Sleep",
      "fields": [
        {
          "key": "needs_sleep",
          "label": "Requires Sleep?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 0,
          "choicesJson": [
            {
              "value": "0",
              "label": "Yes"
            },
            {
              "value": "1",
              "label": "No"
            }
          ]
        },
        {
          "key": "prereview_sleep",
          "label": "PI Suggestions",
          "type": "TEXT",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "prereview_sleep_doc",
          "label": "OR File<br><font size=1>(NOTE: If file will not open, then Save it to your computer and then Open it.)</font>",
          "type": "TEXT",
          "required": false,
          "position": 2,
          "choicesJson": null,
          "note": "Imported from REDCap file-upload field; file uploads are not yet supported."
        },
        {
          "key": "prereview_sleep_date_sent",
          "label": "Date Sent for pre-review",
          "type": "DATE",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "prereview_sleep_date_received",
          "label": "Date received",
          "type": "DATE",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "prereview_sleep_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 5,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "prereview_nutrition",
      "displayName": "Prereview Nutrition",
      "fields": [
        {
          "key": "needs_nutrition",
          "label": "Requires Nutrition?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 0,
          "choicesJson": [
            {
              "value": "0",
              "label": "Yes"
            },
            {
              "value": "1",
              "label": "No"
            }
          ]
        },
        {
          "key": "prereview_nutrition",
          "label": "PI Suggestions",
          "type": "TEXT",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "prereview_nutrition_doc",
          "label": "OR File<br><font size=1>(NOTE: If file will not open, then Save it to your computer and then Open it.)</font>",
          "type": "TEXT",
          "required": false,
          "position": 2,
          "choicesJson": null,
          "note": "Imported from REDCap file-upload field; file uploads are not yet supported."
        },
        {
          "key": "prereview_nutrition_date_sent",
          "label": "Date Sent for pre-review",
          "type": "DATE",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "prereview_nutrition_date_received",
          "label": "Date received",
          "type": "DATE",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "prereview_nutrition_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 5,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "prereview_community",
      "displayName": "Prereview Community",
      "fields": [
        {
          "key": "needs_community",
          "label": "Requires Community?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 0,
          "choicesJson": [
            {
              "value": "0",
              "label": "Yes"
            },
            {
              "value": "1",
              "label": "No"
            }
          ]
        },
        {
          "key": "prereview_community",
          "label": "PI Suggestions",
          "type": "TEXT",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "prereview_community_doc",
          "label": "OR File<br><font size=1>(NOTE: If file will not open, then Save it to your computer and then Open it.)</font>",
          "type": "TEXT",
          "required": false,
          "position": 2,
          "choicesJson": null,
          "note": "Imported from REDCap file-upload field; file uploads are not yet supported."
        },
        {
          "key": "prereview_community_date_sent",
          "label": "Date Sent for pre-review",
          "type": "DATE",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "prereview_community_date_received",
          "label": "Date received",
          "type": "DATE",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "prereview_community_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 5,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "prereview_ctc",
      "displayName": "Prereview Ctc",
      "fields": [
        {
          "key": "needs_other",
          "label": "Requires Other?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 0,
          "choicesJson": [
            {
              "value": "0",
              "label": "Yes"
            },
            {
              "value": "1",
              "label": "No"
            }
          ]
        },
        {
          "key": "prereview_other",
          "label": "PI Suggestions",
          "type": "TEXT",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "prereview_other_doc",
          "label": "OR File<br><font size=1>(NOTE: If file will not open, then Save it to your computer and then Open it.)</font>",
          "type": "TEXT",
          "required": false,
          "position": 2,
          "choicesJson": null,
          "note": "Imported from REDCap file-upload field; file uploads are not yet supported."
        },
        {
          "key": "prereview_other_date_sent",
          "label": "Date Sent for pre-review",
          "type": "DATE",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "prereview_other_date_received",
          "label": "Date received",
          "type": "DATE",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "prereview_ctc_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 5,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "prereview_pi_response",
      "displayName": "Prereview Pi Response",
      "fields": [
        {
          "key": "needs_pi_response",
          "label": "Requires PI Response?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 0,
          "choicesJson": [
            {
              "value": "0",
              "label": "Yes"
            },
            {
              "value": "1",
              "label": "No"
            }
          ]
        },
        {
          "key": "prereview_pi_response",
          "label": "PI response",
          "type": "TEXT",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "prereview_pi_response_doc",
          "label": "OR File<br><font size=1>(NOTE: If file will not open, then Save it to your computer and then Open it.)</font>",
          "type": "TEXT",
          "required": false,
          "position": 2,
          "choicesJson": null,
          "note": "Imported from REDCap file-upload field; file uploads are not yet supported."
        },
        {
          "key": "prereview_pi_response_date_sent",
          "label": "Date Sent for pre-review",
          "type": "DATE",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "prereview_pi_response_date_received",
          "label": "Date received",
          "type": "DATE",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "prereview_pi_response_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 5,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "post_award_administration",
      "displayName": "Post Award Administration",
      "fields": [
        {
          "key": "src_percent_funded",
          "label": "Percent of request funded (%)",
          "type": "TEXT",
          "required": false,
          "position": 0,
          "choicesJson": null
        },
        {
          "key": "src_total_award_amount",
          "label": "SRC Total Award Amount ($)",
          "type": "TEXT",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "src_letter_date",
          "label": "SRC letter sent",
          "type": "DATE",
          "required": false,
          "position": 2,
          "choicesJson": null
        },
        {
          "key": "src_letter_document",
          "label": "SRC letter",
          "type": "TEXT",
          "required": false,
          "position": 3,
          "choicesJson": null,
          "note": "Imported from REDCap file-upload field; file uploads are not yet supported."
        },
        {
          "key": "src_project_ending",
          "label": "SRC project ending date",
          "type": "DATE",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "src_full_project_period",
          "label": "SRC full project period",
          "type": "DATE",
          "required": false,
          "position": 5,
          "choicesJson": null
        },
        {
          "key": "src_center_number",
          "label": "SRC Center Number - Institutional",
          "type": "TEXT",
          "required": false,
          "position": 6,
          "choicesJson": null
        },
        {
          "key": "src_center_number_ctsa",
          "label": "SRC Center Number - CTSA",
          "type": "TEXT",
          "required": false,
          "position": 7,
          "choicesJson": null
        },
        {
          "key": "src_center_number_crc",
          "label": "SRC Center Number - CRC",
          "type": "TEXT",
          "required": false,
          "position": 8,
          "choicesJson": null
        },
        {
          "key": "src_center_number_dh",
          "label": "D & H Number",
          "type": "TEXT",
          "required": false,
          "position": 9,
          "choicesJson": null
        },
        {
          "key": "comments_src",
          "label": "Comments - SRC Award",
          "type": "TEXT",
          "required": false,
          "position": 10,
          "choicesJson": null
        },
        {
          "key": "crc_facilities",
          "label": "CRC Facilities ($)",
          "type": "TEXT",
          "required": false,
          "position": 11,
          "choicesJson": null
        },
        {
          "key": "crc_personnel",
          "label": "CRC Nursing ($)",
          "type": "TEXT",
          "required": false,
          "position": 12,
          "choicesJson": null
        },
        {
          "key": "crc_cores",
          "label": "CRC Cores ($)",
          "type": "TEXT",
          "required": false,
          "position": 13,
          "choicesJson": null
        },
        {
          "key": "sleep_cores",
          "label": "Sleep Core ($)",
          "type": "TEXT",
          "required": false,
          "position": 14,
          "choicesJson": null
        },
        {
          "key": "vumc_core_facilities",
          "label": "VUMC Core Facilities ($)",
          "type": "TEXT",
          "required": false,
          "position": 15,
          "choicesJson": null
        },
        {
          "key": "personnel",
          "label": "Personnel ($)",
          "type": "TEXT",
          "required": false,
          "position": 16,
          "choicesJson": null
        },
        {
          "key": "equipment",
          "label": "Equipment ($)",
          "type": "TEXT",
          "required": false,
          "position": 17,
          "choicesJson": null
        },
        {
          "key": "misc_services",
          "label": "Misc. Services ($)",
          "type": "TEXT",
          "required": false,
          "position": 18,
          "choicesJson": null
        },
        {
          "key": "hospital_ancillaries",
          "label": "Hospital Ancillaries ($)",
          "type": "TEXT",
          "required": false,
          "position": 19,
          "choicesJson": null
        },
        {
          "key": "victr_status",
          "label": "VICTR Status",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 20,
          "choicesJson": [
            {
              "value": "0",
              "label": "Inactive"
            },
            {
              "value": "1",
              "label": "Active"
            }
          ]
        },
        {
          "key": "src_project_completion",
          "label": "SRC completion date",
          "type": "DATE",
          "required": false,
          "position": 21,
          "choicesJson": null
        },
        {
          "key": "post_award_administration_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 22,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    }
  ]
} as TClinicalTemplate;
