// AUTO-GENERATED by apps/web/modules/clinical/onboarding/scripts/convert-redcap-sql.ts
// Source: redcap/redcap_v15.8.4/Resources/sql/create_demo_db7.sql
// Do not edit by hand — regenerate by running the converter.
import type { TClinicalTemplate } from "../template-types";

export const randomizedClinicalTrialTemplate: TClinicalTemplate = {
  "key": "randomized_clinical_trial",
  "name": "Randomized Clinical Trial",
  "description": "Fully randomized trial with baseline, dosing visits, lab/observation forms, and a closeout visit.",
  "purpose": "research",
  "source": {
    "redcapDemo": "Randomized Clinical Trial",
    "sourceFile": "redcap/redcap_v15.8.4/Resources/sql/create_demo_db7.sql"
  },
  "arms": [
    {
      "name": "Arm 1",
      "position": 0,
      "events": [
        {
          "name": "Event 1",
          "position": 0,
          "dayOffset": 0,
          "windowDays": null,
          "instrumentBindings": [
            {
              "instrumentKey": "demographics",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "randomization_form",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "baseline_data",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "month_1_data",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "month_2_data",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "month_3_data",
              "required": true,
              "repeating": false
            },
            {
              "instrumentKey": "completion_data",
              "required": true,
              "repeating": false
            }
          ]
        }
      ]
    }
  ],
  "instruments": [
    {
      "key": "demographics",
      "displayName": "Demographics",
      "fields": [
        {
          "key": "study_id",
          "label": "Study ID",
          "type": "TEXT",
          "required": false,
          "position": 0,
          "choicesJson": null
        },
        {
          "key": "date_enrolled",
          "label": "Date subject signed consent",
          "type": "DATE",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "first_name",
          "label": "First Name",
          "type": "TEXT",
          "required": false,
          "position": 2,
          "choicesJson": null
        },
        {
          "key": "last_name",
          "label": "Last Name",
          "type": "TEXT",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "dob",
          "label": "Date of birth",
          "type": "DATE",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "ethnicity",
          "label": "Ethnicity",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 5,
          "choicesJson": [
            {
              "value": "0",
              "label": "Hispanic or Latino"
            },
            {
              "value": "1",
              "label": "NOT Hispanic or Latino"
            },
            {
              "value": "2",
              "label": "Unknown / Not Reported"
            }
          ]
        },
        {
          "key": "race",
          "label": "Race",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 6,
          "choicesJson": [
            {
              "value": "0",
              "label": "American Indian/Alaska Native"
            },
            {
              "value": "1",
              "label": "Asian"
            },
            {
              "value": "2",
              "label": "Native Hawaiian or Other Pacific Islander"
            },
            {
              "value": "3",
              "label": "Black or African American"
            },
            {
              "value": "4",
              "label": "White"
            },
            {
              "value": "5",
              "label": "More Than One Race"
            },
            {
              "value": "6",
              "label": "Unknown / Not Reported"
            }
          ]
        },
        {
          "key": "sex",
          "label": "sex",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 7,
          "choicesJson": [
            {
              "value": "0",
              "label": "Female"
            },
            {
              "value": "1",
              "label": "Male"
            },
            {
              "value": "2",
              "label": "Other"
            },
            {
              "value": "3",
              "label": "Prefer not to say"
            }
          ]
        },
        {
          "key": "demographics_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 8,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "randomization_form",
      "displayName": "Randomization Form",
      "fields": [
        {
          "key": "randomization_group",
          "label": "Randomization Group",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 0,
          "choicesJson": [
            {
              "value": "0",
              "label": "Drug A"
            },
            {
              "value": "1",
              "label": "Drug B"
            },
            {
              "value": "2",
              "label": "Drug C"
            }
          ]
        },
        {
          "key": "randomization_form_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 1,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "baseline_data",
      "displayName": "Baseline Data",
      "fields": [
        {
          "key": "date_visit_b",
          "label": "Date of baseline visit",
          "type": "DATE",
          "required": false,
          "position": 0,
          "choicesJson": null
        },
        {
          "key": "date_blood_b",
          "label": "Date blood was drawn",
          "type": "DATE",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "alb_b",
          "label": "Serum Albumin (g/dL)",
          "type": "TEXT",
          "required": false,
          "position": 2,
          "choicesJson": null
        },
        {
          "key": "prealb_b",
          "label": "Serum Prealbumin (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "creat_b",
          "label": "Creatinine (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "npcr_b",
          "label": "Normalized Protein Catabolic Rate (g/kg/d)",
          "type": "TEXT",
          "required": false,
          "position": 5,
          "choicesJson": null
        },
        {
          "key": "chol_b",
          "label": "Cholesterol (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 6,
          "choicesJson": null
        },
        {
          "key": "transferrin_b",
          "label": "Transferrin (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 7,
          "choicesJson": null
        },
        {
          "key": "kt_v_b",
          "label": "Kt/V",
          "type": "TEXT",
          "required": false,
          "position": 8,
          "choicesJson": null
        },
        {
          "key": "drywt_b",
          "label": "Dry weight (kilograms)",
          "type": "TEXT",
          "required": false,
          "position": 9,
          "choicesJson": null
        },
        {
          "key": "plasma1_b",
          "label": "Collected Plasma 1?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 10,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "plasma2_b",
          "label": "Collected Plasma 2?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 11,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "plasma3_b",
          "label": "Collected Plasma 3?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 12,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "serum1_b",
          "label": "Collected Serum 1?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 13,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "serum2_b",
          "label": "Collected Serum 2?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 14,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "serum3_b",
          "label": "Collected Serum 3?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 15,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "sga_b",
          "label": "Subject Global Assessment (score = 1-7)",
          "type": "TEXT",
          "required": false,
          "position": 16,
          "choicesJson": null
        },
        {
          "key": "date_supplement_dispensed",
          "label": "Date patient begins supplement",
          "type": "DATE",
          "required": false,
          "position": 17,
          "choicesJson": null
        },
        {
          "key": "baseline_data_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 18,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "month_1_data",
      "displayName": "Month 1 Data",
      "fields": [
        {
          "key": "date_visit_1",
          "label": "Date of Month 1 visit",
          "type": "DATE",
          "required": false,
          "position": 0,
          "choicesJson": null
        },
        {
          "key": "alb_1",
          "label": "Serum Albumin (g/dL)",
          "type": "TEXT",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "prealb_1",
          "label": "Serum Prealbumin (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 2,
          "choicesJson": null
        },
        {
          "key": "creat_1",
          "label": "Creatinine (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "npcr_1",
          "label": "Normalized Protein Catabolic Rate (g/kg/d)",
          "type": "TEXT",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "chol_1",
          "label": "Cholesterol (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 5,
          "choicesJson": null
        },
        {
          "key": "transferrin_1",
          "label": "Transferrin (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 6,
          "choicesJson": null
        },
        {
          "key": "kt_v_1",
          "label": "Kt/V",
          "type": "TEXT",
          "required": false,
          "position": 7,
          "choicesJson": null
        },
        {
          "key": "drywt_1",
          "label": "Dry weight (kilograms)",
          "type": "TEXT",
          "required": false,
          "position": 8,
          "choicesJson": null
        },
        {
          "key": "no_show_1",
          "label": "Number of treatments missed",
          "type": "TEXT",
          "required": false,
          "position": 9,
          "choicesJson": null
        },
        {
          "key": "compliance_1",
          "label": "How compliant was the patient in drinking the supplement?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 10,
          "choicesJson": [
            {
              "value": "0",
              "label": "100 percent"
            },
            {
              "value": "1",
              "label": "99-75 percent"
            },
            {
              "value": "2",
              "label": "74-50 percent"
            },
            {
              "value": "3",
              "label": "49-25 percent"
            },
            {
              "value": "4",
              "label": "0-24 percent"
            }
          ]
        },
        {
          "key": "hospit_1",
          "label": "Was patient hospitalized since last visit?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 11,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "cause_hosp_1",
          "label": "What was the cause of hospitalization?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 12,
          "choicesJson": [
            {
              "value": "1",
              "label": "Vascular access related events"
            },
            {
              "value": "2",
              "label": "CVD events"
            },
            {
              "value": "3",
              "label": "Other"
            }
          ]
        },
        {
          "key": "admission_date_1",
          "label": "Date of hospital admission",
          "type": "DATE",
          "required": false,
          "position": 13,
          "choicesJson": null
        },
        {
          "key": "discharge_date_1",
          "label": "Date of hospital discharge",
          "type": "DATE",
          "required": false,
          "position": 14,
          "choicesJson": null
        },
        {
          "key": "discharge_summary_1",
          "label": "Discharge summary in patients binder?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 15,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "death_1",
          "label": "Has patient died since last visit?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 16,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "date_death_1",
          "label": "Date of death",
          "type": "DATE",
          "required": false,
          "position": 17,
          "choicesJson": null
        },
        {
          "key": "cause_death_1",
          "label": "What was the cause of death?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 18,
          "choicesJson": [
            {
              "value": "1",
              "label": "All-cause"
            },
            {
              "value": "2",
              "label": "Cardiovascular"
            }
          ]
        },
        {
          "key": "month_1_data_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 19,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "month_2_data",
      "displayName": "Month 2 Data",
      "fields": [
        {
          "key": "date_visit_2",
          "label": "Date of Month 2 visit",
          "type": "DATE",
          "required": false,
          "position": 0,
          "choicesJson": null
        },
        {
          "key": "alb_2",
          "label": "Serum Albumin (g/dL)",
          "type": "TEXT",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "prealb_2",
          "label": "Serum Prealbumin (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 2,
          "choicesJson": null
        },
        {
          "key": "creat_2",
          "label": "Creatinine (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "npcr_2",
          "label": "Normalized Protein Catabolic Rate (g/kg/d)",
          "type": "TEXT",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "chol_2",
          "label": "Cholesterol (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 5,
          "choicesJson": null
        },
        {
          "key": "transferrin_2",
          "label": "Transferrin (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 6,
          "choicesJson": null
        },
        {
          "key": "kt_v_2",
          "label": "Kt/V",
          "type": "TEXT",
          "required": false,
          "position": 7,
          "choicesJson": null
        },
        {
          "key": "drywt_2",
          "label": "Dry weight (kilograms)",
          "type": "TEXT",
          "required": false,
          "position": 8,
          "choicesJson": null
        },
        {
          "key": "no_show_2",
          "label": "Number of treatments missed",
          "type": "TEXT",
          "required": false,
          "position": 9,
          "choicesJson": null
        },
        {
          "key": "compliance_2",
          "label": "How compliant was the patient in drinking the supplement?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 10,
          "choicesJson": [
            {
              "value": "0",
              "label": "100 percent"
            },
            {
              "value": "1",
              "label": "99-75 percent"
            },
            {
              "value": "2",
              "label": "74-50 percent"
            },
            {
              "value": "3",
              "label": "49-25 percent"
            },
            {
              "value": "4",
              "label": "0-24 percent"
            }
          ]
        },
        {
          "key": "hospit_2",
          "label": "Was patient hospitalized since last visit?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 11,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "cause_hosp_2",
          "label": "What was the cause of hospitalization?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 12,
          "choicesJson": [
            {
              "value": "1",
              "label": "Vascular access related events"
            },
            {
              "value": "2",
              "label": "CVD events"
            },
            {
              "value": "3",
              "label": "Other"
            }
          ]
        },
        {
          "key": "admission_date_2",
          "label": "Date of hospital admission",
          "type": "DATE",
          "required": false,
          "position": 13,
          "choicesJson": null
        },
        {
          "key": "discharge_date_2",
          "label": "Date of hospital discharge",
          "type": "DATE",
          "required": false,
          "position": 14,
          "choicesJson": null
        },
        {
          "key": "discharge_summary_2",
          "label": "Discharge summary in patients binder?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 15,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "death_2",
          "label": "Has patient died since last visit?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 16,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "date_death_2",
          "label": "Date of death",
          "type": "DATE",
          "required": false,
          "position": 17,
          "choicesJson": null
        },
        {
          "key": "cause_death_2",
          "label": "What was the cause of death?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 18,
          "choicesJson": [
            {
              "value": "1",
              "label": "All-cause"
            },
            {
              "value": "2",
              "label": "Cardiovascular"
            }
          ]
        },
        {
          "key": "month_2_data_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 19,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "month_3_data",
      "displayName": "Month 3 Data",
      "fields": [
        {
          "key": "date_visit_3",
          "label": "Date of Month 3 visit",
          "type": "DATE",
          "required": false,
          "position": 0,
          "choicesJson": null
        },
        {
          "key": "date_blood_3",
          "label": "Date blood was drawn",
          "type": "DATE",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "alb_3",
          "label": "Serum Albumin (g/dL)",
          "type": "TEXT",
          "required": false,
          "position": 2,
          "choicesJson": null
        },
        {
          "key": "prealb_3",
          "label": "Serum Prealbumin (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "creat_3",
          "label": "Creatinine (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "npcr_3",
          "label": "Normalized Protein Catabolic Rate (g/kg/d)",
          "type": "TEXT",
          "required": false,
          "position": 5,
          "choicesJson": null
        },
        {
          "key": "chol_3",
          "label": "Cholesterol (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 6,
          "choicesJson": null
        },
        {
          "key": "transferrin_3",
          "label": "Transferrin (mg/dL)",
          "type": "TEXT",
          "required": false,
          "position": 7,
          "choicesJson": null
        },
        {
          "key": "kt_v_3",
          "label": "Kt/V",
          "type": "TEXT",
          "required": false,
          "position": 8,
          "choicesJson": null
        },
        {
          "key": "drywt_3",
          "label": "Dry weight (kilograms)",
          "type": "TEXT",
          "required": false,
          "position": 9,
          "choicesJson": null
        },
        {
          "key": "plasma1_3",
          "label": "Collected Plasma 1?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 10,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "plasma2_3",
          "label": "Collected Plasma 2?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 11,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "plasma3_3",
          "label": "Collected Plasma 3?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 12,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "serum1_3",
          "label": "Collected Serum 1?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 13,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "serum2_3",
          "label": "Collected Serum 2?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 14,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "serum3_3",
          "label": "Collected Serum 3?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 15,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "sga_3",
          "label": "Subject Global Assessment (score = 1-7)",
          "type": "TEXT",
          "required": false,
          "position": 16,
          "choicesJson": null
        },
        {
          "key": "no_show_3",
          "label": "Number of treatments missed",
          "type": "TEXT",
          "required": false,
          "position": 17,
          "choicesJson": null
        },
        {
          "key": "compliance_3",
          "label": "How compliant was the patient in drinking the supplement?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 18,
          "choicesJson": [
            {
              "value": "0",
              "label": "100 percent"
            },
            {
              "value": "1",
              "label": "99-75 percent"
            },
            {
              "value": "2",
              "label": "74-50 percent"
            },
            {
              "value": "3",
              "label": "49-25 percent"
            },
            {
              "value": "4",
              "label": "0-24 percent"
            }
          ]
        },
        {
          "key": "hospit_3",
          "label": "Was patient hospitalized since last visit?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 19,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "cause_hosp_3",
          "label": "What was the cause of hospitalization?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 20,
          "choicesJson": [
            {
              "value": "1",
              "label": "Vascular access related events"
            },
            {
              "value": "2",
              "label": "CVD events"
            },
            {
              "value": "3",
              "label": "Other"
            }
          ]
        },
        {
          "key": "admission_date_3",
          "label": "Date of hospital admission",
          "type": "DATE",
          "required": false,
          "position": 21,
          "choicesJson": null
        },
        {
          "key": "discharge_date_3",
          "label": "Date of hospital discharge",
          "type": "DATE",
          "required": false,
          "position": 22,
          "choicesJson": null
        },
        {
          "key": "discharge_summary_3",
          "label": "Discharge summary in patients binder?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 23,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "death_3",
          "label": "Has patient died since last visit?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 24,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "date_death_3",
          "label": "Date of death",
          "type": "DATE",
          "required": false,
          "position": 25,
          "choicesJson": null
        },
        {
          "key": "cause_death_3",
          "label": "What was the cause of death?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 26,
          "choicesJson": [
            {
              "value": "1",
              "label": "All-cause"
            },
            {
              "value": "2",
              "label": "Cardiovascular"
            }
          ]
        },
        {
          "key": "month_3_data_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 27,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    },
    {
      "key": "completion_data",
      "displayName": "Completion Data",
      "fields": [
        {
          "key": "complete_study",
          "label": "Has patient completed study?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 0,
          "choicesJson": [
            {
              "value": "0",
              "label": "No"
            },
            {
              "value": "1",
              "label": "Yes"
            }
          ]
        },
        {
          "key": "withdraw_date",
          "label": "Put a date if patient withdrew study",
          "type": "DATE",
          "required": false,
          "position": 1,
          "choicesJson": null
        },
        {
          "key": "withdraw_reason",
          "label": "Reason patient withdrew from study",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 2,
          "choicesJson": [
            {
              "value": "0",
              "label": "Non-compliance"
            },
            {
              "value": "1",
              "label": "Did not wish to continue in study"
            },
            {
              "value": "2",
              "label": "Could not tolerate the supplement"
            },
            {
              "value": "3",
              "label": "Hospitalization"
            },
            {
              "value": "4",
              "label": "Other"
            }
          ]
        },
        {
          "key": "complete_study_date",
          "label": "Date of study completion",
          "type": "DATE",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "study_comments",
          "label": "Comments",
          "type": "TEXT",
          "required": false,
          "position": 4,
          "choicesJson": null
        },
        {
          "key": "completion_data_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 5,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    }
  ]
} as TClinicalTemplate;
