// AUTO-GENERATED by apps/web/modules/clinical/onboarding/scripts/convert-redcap-sql.ts
// Source: redcap/redcap_v15.8.4/Resources/sql/create_demo_db12.sql
// Do not edit by hand — regenerate by running the converter.
import type { TClinicalTemplate } from "../template-types";

export const repeatingInstrumentsTemplate: TClinicalTemplate = {
  "key": "repeating_instruments",
  "name": "Repeating Instruments",
  "description": "Captures repeating data such as adverse-event logs. Continium supports repeating bindings on the EventInstrument level.",
  "purpose": "research",
  "source": {
    "redcapDemo": "Repeating Instruments",
    "sourceFile": "redcap/redcap_v15.8.4/Resources/sql/create_demo_db12.sql"
  },
  "arms": [
    {
      "name": "Arm 1",
      "position": 0,
      "events": [
        {
          "name": "Event 1",
          "position": 0,
          "dayOffset": 0,
          "windowDays": null,
          "instrumentBindings": [
            {
              "instrumentKey": "default",
              "required": true,
              "repeating": false
            }
          ]
        }
      ]
    }
  ],
  "instruments": [
    {
      "key": "default",
      "displayName": "Default Form",
      "fields": []
    }
  ]
} as TClinicalTemplate;
