// AUTO-GENERATED by apps/web/modules/clinical/onboarding/scripts/convert-redcap-sql.ts
// Source: redcap/redcap_v15.8.4/Resources/sql/create_demo_db3.sql
// Do not edit by hand — regenerate by running the converter.
import type { TClinicalTemplate } from "../template-types";

export const singleSurveyTemplate: TClinicalTemplate = {
  "key": "single_survey",
  "name": "Single Survey",
  "description": "Lightweight single-instrument study for one-off questionnaires (no visit schedule).",
  "purpose": "operational_support",
  "source": {
    "redcapDemo": "Single Survey",
    "sourceFile": "redcap/redcap_v15.8.4/Resources/sql/create_demo_db3.sql"
  },
  "arms": [
    {
      "name": "Arm 1",
      "position": 0,
      "events": [
        {
          "name": "Event 1",
          "position": 0,
          "dayOffset": 0,
          "windowDays": null,
          "instrumentBindings": [
            {
              "instrumentKey": "survey",
              "required": true,
              "repeating": false
            }
          ]
        }
      ]
    }
  ],
  "instruments": [
    {
      "key": "survey",
      "displayName": "Survey",
      "fields": [
        {
          "key": "participant_id",
          "label": "Participant ID",
          "type": "TEXT",
          "required": false,
          "position": 0,
          "choicesJson": null
        },
        {
          "key": "radio",
          "label": "You may create MULTIPLE CHOICE questions and set the answer choices for them. You can have as many answer choices as you need. This multiple choice question is rendered as RADIO buttons.",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 1,
          "choicesJson": [
            {
              "value": "1",
              "label": "Choice One"
            },
            {
              "value": "2",
              "label": "Choice Two"
            },
            {
              "value": "3",
              "label": "Choice Three"
            },
            {
              "value": "4",
              "label": "Etc."
            }
          ]
        },
        {
          "key": "dropdown",
          "label": "You may also set multiple choice questions as DROP-DOWN MENUs.",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 2,
          "choicesJson": [
            {
              "value": "1",
              "label": "Choice One"
            },
            {
              "value": "2",
              "label": "Choice Two"
            },
            {
              "value": "3",
              "label": "Choice Three"
            },
            {
              "value": "4",
              "label": "Etc."
            }
          ]
        },
        {
          "key": "textbox",
          "label": "This is a TEXT BOX, which allows respondents to enter a small amount of text. A Text Box can be validated, if needed, as a number, integer, phone number, email, or zipcode. If validated as a number or integer, you may also set the minimum and/or maximum allowable values.\\n\\nThis question has \"number\" validation set with a minimum of 1 and a maximum of 10. ",
          "type": "TEXT",
          "required": false,
          "position": 3,
          "choicesJson": null
        },
        {
          "key": "ma",
          "label": "This type of multiple choice question, known as CHECKBOXES, allows for more than one answer choice to be selected, whereas radio buttons and drop-downs only allow for one choice.",
          "type": "MULTI_SELECT",
          "required": false,
          "position": 4,
          "choicesJson": [
            {
              "value": "1",
              "label": "Choice One"
            },
            {
              "value": "2",
              "label": "Choice Two"
            },
            {
              "value": "3",
              "label": "Choice Three"
            },
            {
              "value": "4",
              "label": "Select as many as you like"
            }
          ]
        },
        {
          "key": "yn",
          "label": "You can create YES-NO questions.<br><br>This question has vertical alignment of choices on the right.",
          "type": "BOOLEAN",
          "required": false,
          "position": 5,
          "choicesJson": null
        },
        {
          "key": "tf",
          "label": "And you can also create TRUE-FALSE questions.<br><br>This question has horizontal alignment.",
          "type": "BOOLEAN",
          "required": false,
          "position": 6,
          "choicesJson": null
        },
        {
          "key": "date_ymd",
          "label": "DATE questions are also an option. If you click the calendar icon on the right, a pop-up calendar will appear, thus allowing the respondent to easily select a date. Or it can be simply typed in.",
          "type": "DATE",
          "required": false,
          "position": 7,
          "choicesJson": null
        },
        {
          "key": "file",
          "label": "The FILE UPLOAD question type allows respondents to upload any type of document to the survey that you may afterward download and open when viewing your survey results.",
          "type": "TEXT",
          "required": false,
          "position": 8,
          "choicesJson": null,
          "note": "Imported from REDCap file-upload field; file uploads are not yet supported."
        },
        {
          "key": "slider",
          "label": "A SLIDER is a question type that allows the respondent to choose an answer along a continuum. The respondent''s answer is saved as an integer between 0 (far left) and 100 (far right) with a step of 1.",
          "type": "NUMBER",
          "required": false,
          "position": 9,
          "choicesJson": null,
          "note": "Imported from REDCap slider field; rendered as a numeric input."
        },
        {
          "key": "descriptive",
          "label": "You may also use DESCRIPTIVE TEXT to provide informational text within a survey section. ",
          "type": "TEXT",
          "required": false,
          "position": 10,
          "choicesJson": null,
          "note": "Imported from REDCap descriptive field; behaves as a static label."
        },
        {
          "key": "gym",
          "label": "Gym (Weight Training)",
          "type": "MULTI_SELECT",
          "required": false,
          "position": 11,
          "choicesJson": [
            {
              "value": "0",
              "label": "Monday"
            },
            {
              "value": "1",
              "label": "Tuesday"
            },
            {
              "value": "2",
              "label": "Wednesday"
            },
            {
              "value": "3",
              "label": "Thursday"
            },
            {
              "value": "4",
              "label": "Friday"
            }
          ]
        },
        {
          "key": "aerobics",
          "label": "Aerobics",
          "type": "MULTI_SELECT",
          "required": false,
          "position": 12,
          "choicesJson": [
            {
              "value": "0",
              "label": "Monday"
            },
            {
              "value": "1",
              "label": "Tuesday"
            },
            {
              "value": "2",
              "label": "Wednesday"
            },
            {
              "value": "3",
              "label": "Thursday"
            },
            {
              "value": "4",
              "label": "Friday"
            }
          ]
        },
        {
          "key": "eat",
          "label": "Eat Out (Dinner/Lunch)",
          "type": "MULTI_SELECT",
          "required": false,
          "position": 13,
          "choicesJson": [
            {
              "value": "0",
              "label": "Monday"
            },
            {
              "value": "1",
              "label": "Tuesday"
            },
            {
              "value": "2",
              "label": "Wednesday"
            },
            {
              "value": "3",
              "label": "Thursday"
            },
            {
              "value": "4",
              "label": "Friday"
            }
          ]
        },
        {
          "key": "drink",
          "label": "Drink (Alcoholic Beverages)",
          "type": "MULTI_SELECT",
          "required": false,
          "position": 14,
          "choicesJson": [
            {
              "value": "0",
              "label": "Monday"
            },
            {
              "value": "1",
              "label": "Tuesday"
            },
            {
              "value": "2",
              "label": "Wednesday"
            },
            {
              "value": "3",
              "label": "Thursday"
            },
            {
              "value": "4",
              "label": "Friday"
            }
          ]
        },
        {
          "key": "radio_branch",
          "label": "BRANCHING LOGIC: The question immediately following this one is using branching logic, which means that the question will stay hidden until defined criteria are specified.\\n\\nFor example, the following question has been set NOT to appear until the respondent selects the second option to the right.  ",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 15,
          "choicesJson": [
            {
              "value": "1",
              "label": "This option does nothing."
            },
            {
              "value": "2",
              "label": "Clicking this option will trigger the branching logic to reveal the next question."
            },
            {
              "value": "3",
              "label": "This option also does nothing."
            }
          ]
        },
        {
          "key": "hidden_branch",
          "label": "HIDDEN QUESTION: This question will only appear when you select the second option of the question immediately above.",
          "type": "TEXT",
          "required": false,
          "position": 16,
          "choicesJson": null
        },
        {
          "key": "stop_actions",
          "label": "STOP ACTIONS may be used with any multiple choice question. Stop actions can be applied to any (or all) answer choices. When that answer choice is selected by a respondent, their survey responses are then saved, and the survey is immediately ended.\\n\\nThe third option to the right has a stop action.",
          "type": "MULTI_SELECT",
          "required": false,
          "position": 17,
          "choicesJson": [
            {
              "value": "1",
              "label": "This option does nothing."
            },
            {
              "value": "2",
              "label": "This option also does nothing."
            },
            {
              "value": "3",
              "label": "Click here to trigger the stop action and end the survey."
            }
          ]
        },
        {
          "key": "comment_box",
          "label": "If you need the respondent to enter a large amount of text, you may use a NOTES BOX.<br><br>This question has also been set as a REQUIRED QUESTION, so the respondent cannot fully submit the survey until this question has been answered. ANY question type can be set to be required.",
          "type": "TEXT",
          "required": false,
          "position": 18,
          "choicesJson": null
        },
        {
          "key": "survey_complete",
          "label": "Complete?",
          "type": "SINGLE_SELECT",
          "required": false,
          "position": 19,
          "choicesJson": [
            {
              "value": "0",
              "label": "Incomplete"
            },
            {
              "value": "1",
              "label": "Unverified"
            },
            {
              "value": "2",
              "label": "Complete"
            }
          ]
        }
      ]
    }
  ]
} as TClinicalTemplate;
